// Code generated by ent, DO NOT EDIT.

package sysrole

import (
	"go-ent-demo/entcore/predicate"
	"go-ent-demo/types"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id types.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id types.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id types.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...types.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...types.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id types.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id types.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id types.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id types.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldID, id))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldSort, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldStatus, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDeletedAt, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldRemark, v))
}

// RoleName applies equality check predicate on the "role_name" field. It's identical to RoleNameEQ.
func RoleName(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldRoleName, v))
}

// RoleCode applies equality check predicate on the "role_code" field. It's identical to RoleCodeEQ.
func RoleCode(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldRoleCode, v))
}

// MenuCheckStrictly applies equality check predicate on the "menu_check_strictly" field. It's identical to MenuCheckStrictlyEQ.
func MenuCheckStrictly(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldMenuCheckStrictly, v))
}

// DeptCheckStrictly applies equality check predicate on the "dept_check_strictly" field. It's identical to DeptCheckStrictlyEQ.
func DeptCheckStrictly(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDeptCheckStrictly, v))
}

// DataScope applies equality check predicate on the "data_scope" field. It's identical to DataScopeEQ.
func DataScope(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDataScope, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDescription, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldSort, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v types.CustomTime) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByContains applies the Contains predicate on the "deleted_by" field.
func DeletedByContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldDeletedBy, v))
}

// DeletedByHasPrefix applies the HasPrefix predicate on the "deleted_by" field.
func DeletedByHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldDeletedBy, v))
}

// DeletedByHasSuffix applies the HasSuffix predicate on the "deleted_by" field.
func DeletedByHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedByEqualFold applies the EqualFold predicate on the "deleted_by" field.
func DeletedByEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldDeletedBy, v))
}

// DeletedByContainsFold applies the ContainsFold predicate on the "deleted_by" field.
func DeletedByContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldDeletedBy, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldDeletedAt))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldRemark, v))
}

// RoleNameEQ applies the EQ predicate on the "role_name" field.
func RoleNameEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldRoleName, v))
}

// RoleNameNEQ applies the NEQ predicate on the "role_name" field.
func RoleNameNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldRoleName, v))
}

// RoleNameIn applies the In predicate on the "role_name" field.
func RoleNameIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldRoleName, vs...))
}

// RoleNameNotIn applies the NotIn predicate on the "role_name" field.
func RoleNameNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldRoleName, vs...))
}

// RoleNameGT applies the GT predicate on the "role_name" field.
func RoleNameGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldRoleName, v))
}

// RoleNameGTE applies the GTE predicate on the "role_name" field.
func RoleNameGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldRoleName, v))
}

// RoleNameLT applies the LT predicate on the "role_name" field.
func RoleNameLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldRoleName, v))
}

// RoleNameLTE applies the LTE predicate on the "role_name" field.
func RoleNameLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldRoleName, v))
}

// RoleNameContains applies the Contains predicate on the "role_name" field.
func RoleNameContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldRoleName, v))
}

// RoleNameHasPrefix applies the HasPrefix predicate on the "role_name" field.
func RoleNameHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldRoleName, v))
}

// RoleNameHasSuffix applies the HasSuffix predicate on the "role_name" field.
func RoleNameHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldRoleName, v))
}

// RoleNameIsNil applies the IsNil predicate on the "role_name" field.
func RoleNameIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldRoleName))
}

// RoleNameNotNil applies the NotNil predicate on the "role_name" field.
func RoleNameNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldRoleName))
}

// RoleNameEqualFold applies the EqualFold predicate on the "role_name" field.
func RoleNameEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldRoleName, v))
}

// RoleNameContainsFold applies the ContainsFold predicate on the "role_name" field.
func RoleNameContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldRoleName, v))
}

// RoleCodeEQ applies the EQ predicate on the "role_code" field.
func RoleCodeEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldRoleCode, v))
}

// RoleCodeNEQ applies the NEQ predicate on the "role_code" field.
func RoleCodeNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldRoleCode, v))
}

// RoleCodeIn applies the In predicate on the "role_code" field.
func RoleCodeIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldRoleCode, vs...))
}

// RoleCodeNotIn applies the NotIn predicate on the "role_code" field.
func RoleCodeNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldRoleCode, vs...))
}

// RoleCodeGT applies the GT predicate on the "role_code" field.
func RoleCodeGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldRoleCode, v))
}

// RoleCodeGTE applies the GTE predicate on the "role_code" field.
func RoleCodeGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldRoleCode, v))
}

// RoleCodeLT applies the LT predicate on the "role_code" field.
func RoleCodeLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldRoleCode, v))
}

// RoleCodeLTE applies the LTE predicate on the "role_code" field.
func RoleCodeLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldRoleCode, v))
}

// RoleCodeContains applies the Contains predicate on the "role_code" field.
func RoleCodeContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldRoleCode, v))
}

// RoleCodeHasPrefix applies the HasPrefix predicate on the "role_code" field.
func RoleCodeHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldRoleCode, v))
}

// RoleCodeHasSuffix applies the HasSuffix predicate on the "role_code" field.
func RoleCodeHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldRoleCode, v))
}

// RoleCodeIsNil applies the IsNil predicate on the "role_code" field.
func RoleCodeIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldRoleCode))
}

// RoleCodeNotNil applies the NotNil predicate on the "role_code" field.
func RoleCodeNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldRoleCode))
}

// RoleCodeEqualFold applies the EqualFold predicate on the "role_code" field.
func RoleCodeEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldRoleCode, v))
}

// RoleCodeContainsFold applies the ContainsFold predicate on the "role_code" field.
func RoleCodeContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldRoleCode, v))
}

// MenuCheckStrictlyEQ applies the EQ predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyEQ(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyNEQ applies the NEQ predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyNEQ(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyIn applies the In predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyIn(vs ...int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldMenuCheckStrictly, vs...))
}

// MenuCheckStrictlyNotIn applies the NotIn predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyNotIn(vs ...int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldMenuCheckStrictly, vs...))
}

// MenuCheckStrictlyGT applies the GT predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyGT(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyGTE applies the GTE predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyGTE(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyLT applies the LT predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyLT(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyLTE applies the LTE predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyLTE(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldMenuCheckStrictly, v))
}

// DeptCheckStrictlyEQ applies the EQ predicate on the "dept_check_strictly" field.
func DeptCheckStrictlyEQ(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDeptCheckStrictly, v))
}

// DeptCheckStrictlyNEQ applies the NEQ predicate on the "dept_check_strictly" field.
func DeptCheckStrictlyNEQ(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldDeptCheckStrictly, v))
}

// DeptCheckStrictlyIn applies the In predicate on the "dept_check_strictly" field.
func DeptCheckStrictlyIn(vs ...int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldDeptCheckStrictly, vs...))
}

// DeptCheckStrictlyNotIn applies the NotIn predicate on the "dept_check_strictly" field.
func DeptCheckStrictlyNotIn(vs ...int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldDeptCheckStrictly, vs...))
}

// DeptCheckStrictlyGT applies the GT predicate on the "dept_check_strictly" field.
func DeptCheckStrictlyGT(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldDeptCheckStrictly, v))
}

// DeptCheckStrictlyGTE applies the GTE predicate on the "dept_check_strictly" field.
func DeptCheckStrictlyGTE(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldDeptCheckStrictly, v))
}

// DeptCheckStrictlyLT applies the LT predicate on the "dept_check_strictly" field.
func DeptCheckStrictlyLT(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldDeptCheckStrictly, v))
}

// DeptCheckStrictlyLTE applies the LTE predicate on the "dept_check_strictly" field.
func DeptCheckStrictlyLTE(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldDeptCheckStrictly, v))
}

// DataScopeEQ applies the EQ predicate on the "data_scope" field.
func DataScopeEQ(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDataScope, v))
}

// DataScopeNEQ applies the NEQ predicate on the "data_scope" field.
func DataScopeNEQ(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldDataScope, v))
}

// DataScopeIn applies the In predicate on the "data_scope" field.
func DataScopeIn(vs ...int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldDataScope, vs...))
}

// DataScopeNotIn applies the NotIn predicate on the "data_scope" field.
func DataScopeNotIn(vs ...int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldDataScope, vs...))
}

// DataScopeGT applies the GT predicate on the "data_scope" field.
func DataScopeGT(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldDataScope, v))
}

// DataScopeGTE applies the GTE predicate on the "data_scope" field.
func DataScopeGTE(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldDataScope, v))
}

// DataScopeLT applies the LT predicate on the "data_scope" field.
func DataScopeLT(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldDataScope, v))
}

// DataScopeLTE applies the LTE predicate on the "data_scope" field.
func DataScopeLTE(v int8) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldDataScope, v))
}

// DataScopeIsNil applies the IsNil predicate on the "data_scope" field.
func DataScopeIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldDataScope))
}

// DataScopeNotNil applies the NotNil predicate on the "data_scope" field.
func DataScopeNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldDataScope))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldDescription, v))
}

// HasSysDepts applies the HasEdge predicate on the "sysDepts" edge.
func HasSysDepts() predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, SysDeptsTable, SysDeptsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSysDeptsWith applies the HasEdge predicate on the "sysDepts" edge with a given conditions (other predicates).
func HasSysDeptsWith(preds ...predicate.SysDept) predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := newSysDeptsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSysUsers applies the HasEdge predicate on the "sysUsers" edge.
func HasSysUsers() predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, SysUsersTable, SysUsersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSysUsersWith applies the HasEdge predicate on the "sysUsers" edge with a given conditions (other predicates).
func HasSysUsersWith(preds ...predicate.SysUser) predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := newSysUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSysMenus applies the HasEdge predicate on the "sysMenus" edge.
func HasSysMenus() predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, SysMenusTable, SysMenusPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSysMenusWith applies the HasEdge predicate on the "sysMenus" edge with a given conditions (other predicates).
func HasSysMenusWith(preds ...predicate.SysMenu) predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := newSysMenusStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysRole) predicate.SysRole {
	return predicate.SysRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysRole) predicate.SysRole {
	return predicate.SysRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysRole) predicate.SysRole {
	return predicate.SysRole(sql.NotPredicates(p))
}
