// Code generated by ent, DO NOT EDIT.

package sysmenu

import (
	"go-ent-demo/entcore/predicate"
	"go-ent-demo/types"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldID, id))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldParentID, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldSort, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldStatus, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldDeletedAt, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldRemark, v))
}

// DelFlag applies equality check predicate on the "del_flag" field. It's identical to DelFlagEQ.
func DelFlag(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldDelFlag, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldName, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldPath, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldType, v))
}

// Component applies equality check predicate on the "component" field. It's identical to ComponentEQ.
func Component(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldComponent, v))
}

// Permission applies equality check predicate on the "permission" field. It's identical to PermissionEQ.
func Permission(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldPermission, v))
}

// Redirect applies equality check predicate on the "redirect" field. It's identical to RedirectEQ.
func Redirect(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldRedirect, v))
}

// MetaTitle applies equality check predicate on the "meta_title" field. It's identical to MetaTitleEQ.
func MetaTitle(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaTitle, v))
}

// MetaIcon applies equality check predicate on the "meta_icon" field. It's identical to MetaIconEQ.
func MetaIcon(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaIcon, v))
}

// MetaActiveIcon applies equality check predicate on the "meta_active_icon" field. It's identical to MetaActiveIconEQ.
func MetaActiveIcon(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaActiveIcon, v))
}

// MetaKeepAlive applies equality check predicate on the "meta_keep_alive" field. It's identical to MetaKeepAliveEQ.
func MetaKeepAlive(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaKeepAlive, v))
}

// MetaHideInMenu applies equality check predicate on the "meta_hide_in_menu" field. It's identical to MetaHideInMenuEQ.
func MetaHideInMenu(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaHideInMenu, v))
}

// MetaHideInTab applies equality check predicate on the "meta_hide_in_tab" field. It's identical to MetaHideInTabEQ.
func MetaHideInTab(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaHideInTab, v))
}

// MetaHideInBreadcrumb applies equality check predicate on the "meta_hide_in_breadcrumb" field. It's identical to MetaHideInBreadcrumbEQ.
func MetaHideInBreadcrumb(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaHideInBreadcrumb, v))
}

// MetaHideChildrenInMenu applies equality check predicate on the "meta_hide_children_in_menu" field. It's identical to MetaHideChildrenInMenuEQ.
func MetaHideChildrenInMenu(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaHideChildrenInMenu, v))
}

// MetaAuthority applies equality check predicate on the "meta_authority" field. It's identical to MetaAuthorityEQ.
func MetaAuthority(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaAuthority, v))
}

// MetaBadge applies equality check predicate on the "meta_badge" field. It's identical to MetaBadgeEQ.
func MetaBadge(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaBadge, v))
}

// MetaBadgeType applies equality check predicate on the "meta_badge_type" field. It's identical to MetaBadgeTypeEQ.
func MetaBadgeType(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaBadgeType, v))
}

// MetaBadgeVariants applies equality check predicate on the "meta_badge_variants" field. It's identical to MetaBadgeVariantsEQ.
func MetaBadgeVariants(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaBadgeVariants, v))
}

// MetaFullPathKey applies equality check predicate on the "meta_full_path_key" field. It's identical to MetaFullPathKeyEQ.
func MetaFullPathKey(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaFullPathKey, v))
}

// MetaActivePath applies equality check predicate on the "meta_active_path" field. It's identical to MetaActivePathEQ.
func MetaActivePath(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaActivePath, v))
}

// MetaAffixTab applies equality check predicate on the "meta_affix_tab" field. It's identical to MetaAffixTabEQ.
func MetaAffixTab(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaAffixTab, v))
}

// MetaAffixTabOrder applies equality check predicate on the "meta_affix_tab_order" field. It's identical to MetaAffixTabOrderEQ.
func MetaAffixTabOrder(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaAffixTabOrder, v))
}

// MetaIframeSrc applies equality check predicate on the "meta_iframe_src" field. It's identical to MetaIframeSrcEQ.
func MetaIframeSrc(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaIframeSrc, v))
}

// MetaIgnoreAccess applies equality check predicate on the "meta_ignore_access" field. It's identical to MetaIgnoreAccessEQ.
func MetaIgnoreAccess(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaIgnoreAccess, v))
}

// MetaLink applies equality check predicate on the "meta_link" field. It's identical to MetaLinkEQ.
func MetaLink(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaLink, v))
}

// MetaMaxNumOfOpenTab applies equality check predicate on the "meta_max_num_of_open_tab" field. It's identical to MetaMaxNumOfOpenTabEQ.
func MetaMaxNumOfOpenTab(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaMaxNumOfOpenTab, v))
}

// MetaMenuVisibleWithForbidden applies equality check predicate on the "meta_menu_visible_with_forbidden" field. It's identical to MetaMenuVisibleWithForbiddenEQ.
func MetaMenuVisibleWithForbidden(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaMenuVisibleWithForbidden, v))
}

// MetaOpenInNewWindow applies equality check predicate on the "meta_open_in_new_window" field. It's identical to MetaOpenInNewWindowEQ.
func MetaOpenInNewWindow(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaOpenInNewWindow, v))
}

// MetaOrder applies equality check predicate on the "meta_order" field. It's identical to MetaOrderEQ.
func MetaOrder(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaOrder, v))
}

// MetaQuery applies equality check predicate on the "meta_query" field. It's identical to MetaQueryEQ.
func MetaQuery(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaQuery, v))
}

// MetaNoBasicLayout applies equality check predicate on the "meta_no_basic_layout" field. It's identical to MetaNoBasicLayoutEQ.
func MetaNoBasicLayout(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaNoBasicLayout, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...types.ID) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldParentID))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldSort, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v types.CustomTime) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByContains applies the Contains predicate on the "deleted_by" field.
func DeletedByContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldDeletedBy, v))
}

// DeletedByHasPrefix applies the HasPrefix predicate on the "deleted_by" field.
func DeletedByHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldDeletedBy, v))
}

// DeletedByHasSuffix applies the HasSuffix predicate on the "deleted_by" field.
func DeletedByHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedByEqualFold applies the EqualFold predicate on the "deleted_by" field.
func DeletedByEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldDeletedBy, v))
}

// DeletedByContainsFold applies the ContainsFold predicate on the "deleted_by" field.
func DeletedByContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldDeletedBy, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldDeletedAt))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldRemark, v))
}

// DelFlagEQ applies the EQ predicate on the "del_flag" field.
func DelFlagEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldDelFlag, v))
}

// DelFlagNEQ applies the NEQ predicate on the "del_flag" field.
func DelFlagNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldDelFlag, v))
}

// DelFlagIn applies the In predicate on the "del_flag" field.
func DelFlagIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldDelFlag, vs...))
}

// DelFlagNotIn applies the NotIn predicate on the "del_flag" field.
func DelFlagNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldDelFlag, vs...))
}

// DelFlagGT applies the GT predicate on the "del_flag" field.
func DelFlagGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldDelFlag, v))
}

// DelFlagGTE applies the GTE predicate on the "del_flag" field.
func DelFlagGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldDelFlag, v))
}

// DelFlagLT applies the LT predicate on the "del_flag" field.
func DelFlagLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldDelFlag, v))
}

// DelFlagLTE applies the LTE predicate on the "del_flag" field.
func DelFlagLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldDelFlag, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldName, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldPath, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldPath))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldPath, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldType, v))
}

// ComponentEQ applies the EQ predicate on the "component" field.
func ComponentEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldComponent, v))
}

// ComponentNEQ applies the NEQ predicate on the "component" field.
func ComponentNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldComponent, v))
}

// ComponentIn applies the In predicate on the "component" field.
func ComponentIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldComponent, vs...))
}

// ComponentNotIn applies the NotIn predicate on the "component" field.
func ComponentNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldComponent, vs...))
}

// ComponentGT applies the GT predicate on the "component" field.
func ComponentGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldComponent, v))
}

// ComponentGTE applies the GTE predicate on the "component" field.
func ComponentGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldComponent, v))
}

// ComponentLT applies the LT predicate on the "component" field.
func ComponentLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldComponent, v))
}

// ComponentLTE applies the LTE predicate on the "component" field.
func ComponentLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldComponent, v))
}

// ComponentContains applies the Contains predicate on the "component" field.
func ComponentContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldComponent, v))
}

// ComponentHasPrefix applies the HasPrefix predicate on the "component" field.
func ComponentHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldComponent, v))
}

// ComponentHasSuffix applies the HasSuffix predicate on the "component" field.
func ComponentHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldComponent, v))
}

// ComponentEqualFold applies the EqualFold predicate on the "component" field.
func ComponentEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldComponent, v))
}

// ComponentContainsFold applies the ContainsFold predicate on the "component" field.
func ComponentContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldComponent, v))
}

// PermissionEQ applies the EQ predicate on the "permission" field.
func PermissionEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldPermission, v))
}

// PermissionNEQ applies the NEQ predicate on the "permission" field.
func PermissionNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldPermission, v))
}

// PermissionIn applies the In predicate on the "permission" field.
func PermissionIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldPermission, vs...))
}

// PermissionNotIn applies the NotIn predicate on the "permission" field.
func PermissionNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldPermission, vs...))
}

// PermissionGT applies the GT predicate on the "permission" field.
func PermissionGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldPermission, v))
}

// PermissionGTE applies the GTE predicate on the "permission" field.
func PermissionGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldPermission, v))
}

// PermissionLT applies the LT predicate on the "permission" field.
func PermissionLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldPermission, v))
}

// PermissionLTE applies the LTE predicate on the "permission" field.
func PermissionLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldPermission, v))
}

// PermissionContains applies the Contains predicate on the "permission" field.
func PermissionContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldPermission, v))
}

// PermissionHasPrefix applies the HasPrefix predicate on the "permission" field.
func PermissionHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldPermission, v))
}

// PermissionHasSuffix applies the HasSuffix predicate on the "permission" field.
func PermissionHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldPermission, v))
}

// PermissionIsNil applies the IsNil predicate on the "permission" field.
func PermissionIsNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIsNull(FieldPermission))
}

// PermissionNotNil applies the NotNil predicate on the "permission" field.
func PermissionNotNil() predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotNull(FieldPermission))
}

// PermissionEqualFold applies the EqualFold predicate on the "permission" field.
func PermissionEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldPermission, v))
}

// PermissionContainsFold applies the ContainsFold predicate on the "permission" field.
func PermissionContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldPermission, v))
}

// RedirectEQ applies the EQ predicate on the "redirect" field.
func RedirectEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldRedirect, v))
}

// RedirectNEQ applies the NEQ predicate on the "redirect" field.
func RedirectNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldRedirect, v))
}

// RedirectIn applies the In predicate on the "redirect" field.
func RedirectIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldRedirect, vs...))
}

// RedirectNotIn applies the NotIn predicate on the "redirect" field.
func RedirectNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldRedirect, vs...))
}

// RedirectGT applies the GT predicate on the "redirect" field.
func RedirectGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldRedirect, v))
}

// RedirectGTE applies the GTE predicate on the "redirect" field.
func RedirectGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldRedirect, v))
}

// RedirectLT applies the LT predicate on the "redirect" field.
func RedirectLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldRedirect, v))
}

// RedirectLTE applies the LTE predicate on the "redirect" field.
func RedirectLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldRedirect, v))
}

// RedirectContains applies the Contains predicate on the "redirect" field.
func RedirectContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldRedirect, v))
}

// RedirectHasPrefix applies the HasPrefix predicate on the "redirect" field.
func RedirectHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldRedirect, v))
}

// RedirectHasSuffix applies the HasSuffix predicate on the "redirect" field.
func RedirectHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldRedirect, v))
}

// RedirectEqualFold applies the EqualFold predicate on the "redirect" field.
func RedirectEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldRedirect, v))
}

// RedirectContainsFold applies the ContainsFold predicate on the "redirect" field.
func RedirectContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldRedirect, v))
}

// MetaTitleEQ applies the EQ predicate on the "meta_title" field.
func MetaTitleEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaTitle, v))
}

// MetaTitleNEQ applies the NEQ predicate on the "meta_title" field.
func MetaTitleNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaTitle, v))
}

// MetaTitleIn applies the In predicate on the "meta_title" field.
func MetaTitleIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaTitle, vs...))
}

// MetaTitleNotIn applies the NotIn predicate on the "meta_title" field.
func MetaTitleNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaTitle, vs...))
}

// MetaTitleGT applies the GT predicate on the "meta_title" field.
func MetaTitleGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaTitle, v))
}

// MetaTitleGTE applies the GTE predicate on the "meta_title" field.
func MetaTitleGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaTitle, v))
}

// MetaTitleLT applies the LT predicate on the "meta_title" field.
func MetaTitleLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaTitle, v))
}

// MetaTitleLTE applies the LTE predicate on the "meta_title" field.
func MetaTitleLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaTitle, v))
}

// MetaTitleContains applies the Contains predicate on the "meta_title" field.
func MetaTitleContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldMetaTitle, v))
}

// MetaTitleHasPrefix applies the HasPrefix predicate on the "meta_title" field.
func MetaTitleHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldMetaTitle, v))
}

// MetaTitleHasSuffix applies the HasSuffix predicate on the "meta_title" field.
func MetaTitleHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldMetaTitle, v))
}

// MetaTitleEqualFold applies the EqualFold predicate on the "meta_title" field.
func MetaTitleEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldMetaTitle, v))
}

// MetaTitleContainsFold applies the ContainsFold predicate on the "meta_title" field.
func MetaTitleContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldMetaTitle, v))
}

// MetaIconEQ applies the EQ predicate on the "meta_icon" field.
func MetaIconEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaIcon, v))
}

// MetaIconNEQ applies the NEQ predicate on the "meta_icon" field.
func MetaIconNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaIcon, v))
}

// MetaIconIn applies the In predicate on the "meta_icon" field.
func MetaIconIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaIcon, vs...))
}

// MetaIconNotIn applies the NotIn predicate on the "meta_icon" field.
func MetaIconNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaIcon, vs...))
}

// MetaIconGT applies the GT predicate on the "meta_icon" field.
func MetaIconGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaIcon, v))
}

// MetaIconGTE applies the GTE predicate on the "meta_icon" field.
func MetaIconGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaIcon, v))
}

// MetaIconLT applies the LT predicate on the "meta_icon" field.
func MetaIconLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaIcon, v))
}

// MetaIconLTE applies the LTE predicate on the "meta_icon" field.
func MetaIconLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaIcon, v))
}

// MetaIconContains applies the Contains predicate on the "meta_icon" field.
func MetaIconContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldMetaIcon, v))
}

// MetaIconHasPrefix applies the HasPrefix predicate on the "meta_icon" field.
func MetaIconHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldMetaIcon, v))
}

// MetaIconHasSuffix applies the HasSuffix predicate on the "meta_icon" field.
func MetaIconHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldMetaIcon, v))
}

// MetaIconEqualFold applies the EqualFold predicate on the "meta_icon" field.
func MetaIconEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldMetaIcon, v))
}

// MetaIconContainsFold applies the ContainsFold predicate on the "meta_icon" field.
func MetaIconContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldMetaIcon, v))
}

// MetaActiveIconEQ applies the EQ predicate on the "meta_active_icon" field.
func MetaActiveIconEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaActiveIcon, v))
}

// MetaActiveIconNEQ applies the NEQ predicate on the "meta_active_icon" field.
func MetaActiveIconNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaActiveIcon, v))
}

// MetaActiveIconIn applies the In predicate on the "meta_active_icon" field.
func MetaActiveIconIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaActiveIcon, vs...))
}

// MetaActiveIconNotIn applies the NotIn predicate on the "meta_active_icon" field.
func MetaActiveIconNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaActiveIcon, vs...))
}

// MetaActiveIconGT applies the GT predicate on the "meta_active_icon" field.
func MetaActiveIconGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaActiveIcon, v))
}

// MetaActiveIconGTE applies the GTE predicate on the "meta_active_icon" field.
func MetaActiveIconGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaActiveIcon, v))
}

// MetaActiveIconLT applies the LT predicate on the "meta_active_icon" field.
func MetaActiveIconLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaActiveIcon, v))
}

// MetaActiveIconLTE applies the LTE predicate on the "meta_active_icon" field.
func MetaActiveIconLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaActiveIcon, v))
}

// MetaActiveIconContains applies the Contains predicate on the "meta_active_icon" field.
func MetaActiveIconContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldMetaActiveIcon, v))
}

// MetaActiveIconHasPrefix applies the HasPrefix predicate on the "meta_active_icon" field.
func MetaActiveIconHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldMetaActiveIcon, v))
}

// MetaActiveIconHasSuffix applies the HasSuffix predicate on the "meta_active_icon" field.
func MetaActiveIconHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldMetaActiveIcon, v))
}

// MetaActiveIconEqualFold applies the EqualFold predicate on the "meta_active_icon" field.
func MetaActiveIconEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldMetaActiveIcon, v))
}

// MetaActiveIconContainsFold applies the ContainsFold predicate on the "meta_active_icon" field.
func MetaActiveIconContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldMetaActiveIcon, v))
}

// MetaKeepAliveEQ applies the EQ predicate on the "meta_keep_alive" field.
func MetaKeepAliveEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaKeepAlive, v))
}

// MetaKeepAliveNEQ applies the NEQ predicate on the "meta_keep_alive" field.
func MetaKeepAliveNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaKeepAlive, v))
}

// MetaKeepAliveIn applies the In predicate on the "meta_keep_alive" field.
func MetaKeepAliveIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaKeepAlive, vs...))
}

// MetaKeepAliveNotIn applies the NotIn predicate on the "meta_keep_alive" field.
func MetaKeepAliveNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaKeepAlive, vs...))
}

// MetaKeepAliveGT applies the GT predicate on the "meta_keep_alive" field.
func MetaKeepAliveGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaKeepAlive, v))
}

// MetaKeepAliveGTE applies the GTE predicate on the "meta_keep_alive" field.
func MetaKeepAliveGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaKeepAlive, v))
}

// MetaKeepAliveLT applies the LT predicate on the "meta_keep_alive" field.
func MetaKeepAliveLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaKeepAlive, v))
}

// MetaKeepAliveLTE applies the LTE predicate on the "meta_keep_alive" field.
func MetaKeepAliveLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaKeepAlive, v))
}

// MetaHideInMenuEQ applies the EQ predicate on the "meta_hide_in_menu" field.
func MetaHideInMenuEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaHideInMenu, v))
}

// MetaHideInMenuNEQ applies the NEQ predicate on the "meta_hide_in_menu" field.
func MetaHideInMenuNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaHideInMenu, v))
}

// MetaHideInMenuIn applies the In predicate on the "meta_hide_in_menu" field.
func MetaHideInMenuIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaHideInMenu, vs...))
}

// MetaHideInMenuNotIn applies the NotIn predicate on the "meta_hide_in_menu" field.
func MetaHideInMenuNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaHideInMenu, vs...))
}

// MetaHideInMenuGT applies the GT predicate on the "meta_hide_in_menu" field.
func MetaHideInMenuGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaHideInMenu, v))
}

// MetaHideInMenuGTE applies the GTE predicate on the "meta_hide_in_menu" field.
func MetaHideInMenuGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaHideInMenu, v))
}

// MetaHideInMenuLT applies the LT predicate on the "meta_hide_in_menu" field.
func MetaHideInMenuLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaHideInMenu, v))
}

// MetaHideInMenuLTE applies the LTE predicate on the "meta_hide_in_menu" field.
func MetaHideInMenuLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaHideInMenu, v))
}

// MetaHideInTabEQ applies the EQ predicate on the "meta_hide_in_tab" field.
func MetaHideInTabEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaHideInTab, v))
}

// MetaHideInTabNEQ applies the NEQ predicate on the "meta_hide_in_tab" field.
func MetaHideInTabNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaHideInTab, v))
}

// MetaHideInTabIn applies the In predicate on the "meta_hide_in_tab" field.
func MetaHideInTabIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaHideInTab, vs...))
}

// MetaHideInTabNotIn applies the NotIn predicate on the "meta_hide_in_tab" field.
func MetaHideInTabNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaHideInTab, vs...))
}

// MetaHideInTabGT applies the GT predicate on the "meta_hide_in_tab" field.
func MetaHideInTabGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaHideInTab, v))
}

// MetaHideInTabGTE applies the GTE predicate on the "meta_hide_in_tab" field.
func MetaHideInTabGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaHideInTab, v))
}

// MetaHideInTabLT applies the LT predicate on the "meta_hide_in_tab" field.
func MetaHideInTabLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaHideInTab, v))
}

// MetaHideInTabLTE applies the LTE predicate on the "meta_hide_in_tab" field.
func MetaHideInTabLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaHideInTab, v))
}

// MetaHideInBreadcrumbEQ applies the EQ predicate on the "meta_hide_in_breadcrumb" field.
func MetaHideInBreadcrumbEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaHideInBreadcrumb, v))
}

// MetaHideInBreadcrumbNEQ applies the NEQ predicate on the "meta_hide_in_breadcrumb" field.
func MetaHideInBreadcrumbNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaHideInBreadcrumb, v))
}

// MetaHideInBreadcrumbIn applies the In predicate on the "meta_hide_in_breadcrumb" field.
func MetaHideInBreadcrumbIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaHideInBreadcrumb, vs...))
}

// MetaHideInBreadcrumbNotIn applies the NotIn predicate on the "meta_hide_in_breadcrumb" field.
func MetaHideInBreadcrumbNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaHideInBreadcrumb, vs...))
}

// MetaHideInBreadcrumbGT applies the GT predicate on the "meta_hide_in_breadcrumb" field.
func MetaHideInBreadcrumbGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaHideInBreadcrumb, v))
}

// MetaHideInBreadcrumbGTE applies the GTE predicate on the "meta_hide_in_breadcrumb" field.
func MetaHideInBreadcrumbGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaHideInBreadcrumb, v))
}

// MetaHideInBreadcrumbLT applies the LT predicate on the "meta_hide_in_breadcrumb" field.
func MetaHideInBreadcrumbLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaHideInBreadcrumb, v))
}

// MetaHideInBreadcrumbLTE applies the LTE predicate on the "meta_hide_in_breadcrumb" field.
func MetaHideInBreadcrumbLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaHideInBreadcrumb, v))
}

// MetaHideChildrenInMenuEQ applies the EQ predicate on the "meta_hide_children_in_menu" field.
func MetaHideChildrenInMenuEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaHideChildrenInMenu, v))
}

// MetaHideChildrenInMenuNEQ applies the NEQ predicate on the "meta_hide_children_in_menu" field.
func MetaHideChildrenInMenuNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaHideChildrenInMenu, v))
}

// MetaHideChildrenInMenuIn applies the In predicate on the "meta_hide_children_in_menu" field.
func MetaHideChildrenInMenuIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaHideChildrenInMenu, vs...))
}

// MetaHideChildrenInMenuNotIn applies the NotIn predicate on the "meta_hide_children_in_menu" field.
func MetaHideChildrenInMenuNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaHideChildrenInMenu, vs...))
}

// MetaHideChildrenInMenuGT applies the GT predicate on the "meta_hide_children_in_menu" field.
func MetaHideChildrenInMenuGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaHideChildrenInMenu, v))
}

// MetaHideChildrenInMenuGTE applies the GTE predicate on the "meta_hide_children_in_menu" field.
func MetaHideChildrenInMenuGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaHideChildrenInMenu, v))
}

// MetaHideChildrenInMenuLT applies the LT predicate on the "meta_hide_children_in_menu" field.
func MetaHideChildrenInMenuLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaHideChildrenInMenu, v))
}

// MetaHideChildrenInMenuLTE applies the LTE predicate on the "meta_hide_children_in_menu" field.
func MetaHideChildrenInMenuLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaHideChildrenInMenu, v))
}

// MetaAuthorityEQ applies the EQ predicate on the "meta_authority" field.
func MetaAuthorityEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaAuthority, v))
}

// MetaAuthorityNEQ applies the NEQ predicate on the "meta_authority" field.
func MetaAuthorityNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaAuthority, v))
}

// MetaAuthorityIn applies the In predicate on the "meta_authority" field.
func MetaAuthorityIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaAuthority, vs...))
}

// MetaAuthorityNotIn applies the NotIn predicate on the "meta_authority" field.
func MetaAuthorityNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaAuthority, vs...))
}

// MetaAuthorityGT applies the GT predicate on the "meta_authority" field.
func MetaAuthorityGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaAuthority, v))
}

// MetaAuthorityGTE applies the GTE predicate on the "meta_authority" field.
func MetaAuthorityGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaAuthority, v))
}

// MetaAuthorityLT applies the LT predicate on the "meta_authority" field.
func MetaAuthorityLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaAuthority, v))
}

// MetaAuthorityLTE applies the LTE predicate on the "meta_authority" field.
func MetaAuthorityLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaAuthority, v))
}

// MetaAuthorityContains applies the Contains predicate on the "meta_authority" field.
func MetaAuthorityContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldMetaAuthority, v))
}

// MetaAuthorityHasPrefix applies the HasPrefix predicate on the "meta_authority" field.
func MetaAuthorityHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldMetaAuthority, v))
}

// MetaAuthorityHasSuffix applies the HasSuffix predicate on the "meta_authority" field.
func MetaAuthorityHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldMetaAuthority, v))
}

// MetaAuthorityEqualFold applies the EqualFold predicate on the "meta_authority" field.
func MetaAuthorityEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldMetaAuthority, v))
}

// MetaAuthorityContainsFold applies the ContainsFold predicate on the "meta_authority" field.
func MetaAuthorityContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldMetaAuthority, v))
}

// MetaBadgeEQ applies the EQ predicate on the "meta_badge" field.
func MetaBadgeEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaBadge, v))
}

// MetaBadgeNEQ applies the NEQ predicate on the "meta_badge" field.
func MetaBadgeNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaBadge, v))
}

// MetaBadgeIn applies the In predicate on the "meta_badge" field.
func MetaBadgeIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaBadge, vs...))
}

// MetaBadgeNotIn applies the NotIn predicate on the "meta_badge" field.
func MetaBadgeNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaBadge, vs...))
}

// MetaBadgeGT applies the GT predicate on the "meta_badge" field.
func MetaBadgeGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaBadge, v))
}

// MetaBadgeGTE applies the GTE predicate on the "meta_badge" field.
func MetaBadgeGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaBadge, v))
}

// MetaBadgeLT applies the LT predicate on the "meta_badge" field.
func MetaBadgeLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaBadge, v))
}

// MetaBadgeLTE applies the LTE predicate on the "meta_badge" field.
func MetaBadgeLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaBadge, v))
}

// MetaBadgeContains applies the Contains predicate on the "meta_badge" field.
func MetaBadgeContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldMetaBadge, v))
}

// MetaBadgeHasPrefix applies the HasPrefix predicate on the "meta_badge" field.
func MetaBadgeHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldMetaBadge, v))
}

// MetaBadgeHasSuffix applies the HasSuffix predicate on the "meta_badge" field.
func MetaBadgeHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldMetaBadge, v))
}

// MetaBadgeEqualFold applies the EqualFold predicate on the "meta_badge" field.
func MetaBadgeEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldMetaBadge, v))
}

// MetaBadgeContainsFold applies the ContainsFold predicate on the "meta_badge" field.
func MetaBadgeContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldMetaBadge, v))
}

// MetaBadgeTypeEQ applies the EQ predicate on the "meta_badge_type" field.
func MetaBadgeTypeEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaBadgeType, v))
}

// MetaBadgeTypeNEQ applies the NEQ predicate on the "meta_badge_type" field.
func MetaBadgeTypeNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaBadgeType, v))
}

// MetaBadgeTypeIn applies the In predicate on the "meta_badge_type" field.
func MetaBadgeTypeIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaBadgeType, vs...))
}

// MetaBadgeTypeNotIn applies the NotIn predicate on the "meta_badge_type" field.
func MetaBadgeTypeNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaBadgeType, vs...))
}

// MetaBadgeTypeGT applies the GT predicate on the "meta_badge_type" field.
func MetaBadgeTypeGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaBadgeType, v))
}

// MetaBadgeTypeGTE applies the GTE predicate on the "meta_badge_type" field.
func MetaBadgeTypeGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaBadgeType, v))
}

// MetaBadgeTypeLT applies the LT predicate on the "meta_badge_type" field.
func MetaBadgeTypeLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaBadgeType, v))
}

// MetaBadgeTypeLTE applies the LTE predicate on the "meta_badge_type" field.
func MetaBadgeTypeLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaBadgeType, v))
}

// MetaBadgeVariantsEQ applies the EQ predicate on the "meta_badge_variants" field.
func MetaBadgeVariantsEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaBadgeVariants, v))
}

// MetaBadgeVariantsNEQ applies the NEQ predicate on the "meta_badge_variants" field.
func MetaBadgeVariantsNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaBadgeVariants, v))
}

// MetaBadgeVariantsIn applies the In predicate on the "meta_badge_variants" field.
func MetaBadgeVariantsIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaBadgeVariants, vs...))
}

// MetaBadgeVariantsNotIn applies the NotIn predicate on the "meta_badge_variants" field.
func MetaBadgeVariantsNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaBadgeVariants, vs...))
}

// MetaBadgeVariantsGT applies the GT predicate on the "meta_badge_variants" field.
func MetaBadgeVariantsGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaBadgeVariants, v))
}

// MetaBadgeVariantsGTE applies the GTE predicate on the "meta_badge_variants" field.
func MetaBadgeVariantsGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaBadgeVariants, v))
}

// MetaBadgeVariantsLT applies the LT predicate on the "meta_badge_variants" field.
func MetaBadgeVariantsLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaBadgeVariants, v))
}

// MetaBadgeVariantsLTE applies the LTE predicate on the "meta_badge_variants" field.
func MetaBadgeVariantsLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaBadgeVariants, v))
}

// MetaFullPathKeyEQ applies the EQ predicate on the "meta_full_path_key" field.
func MetaFullPathKeyEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaFullPathKey, v))
}

// MetaFullPathKeyNEQ applies the NEQ predicate on the "meta_full_path_key" field.
func MetaFullPathKeyNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaFullPathKey, v))
}

// MetaFullPathKeyIn applies the In predicate on the "meta_full_path_key" field.
func MetaFullPathKeyIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaFullPathKey, vs...))
}

// MetaFullPathKeyNotIn applies the NotIn predicate on the "meta_full_path_key" field.
func MetaFullPathKeyNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaFullPathKey, vs...))
}

// MetaFullPathKeyGT applies the GT predicate on the "meta_full_path_key" field.
func MetaFullPathKeyGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaFullPathKey, v))
}

// MetaFullPathKeyGTE applies the GTE predicate on the "meta_full_path_key" field.
func MetaFullPathKeyGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaFullPathKey, v))
}

// MetaFullPathKeyLT applies the LT predicate on the "meta_full_path_key" field.
func MetaFullPathKeyLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaFullPathKey, v))
}

// MetaFullPathKeyLTE applies the LTE predicate on the "meta_full_path_key" field.
func MetaFullPathKeyLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaFullPathKey, v))
}

// MetaActivePathEQ applies the EQ predicate on the "meta_active_path" field.
func MetaActivePathEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaActivePath, v))
}

// MetaActivePathNEQ applies the NEQ predicate on the "meta_active_path" field.
func MetaActivePathNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaActivePath, v))
}

// MetaActivePathIn applies the In predicate on the "meta_active_path" field.
func MetaActivePathIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaActivePath, vs...))
}

// MetaActivePathNotIn applies the NotIn predicate on the "meta_active_path" field.
func MetaActivePathNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaActivePath, vs...))
}

// MetaActivePathGT applies the GT predicate on the "meta_active_path" field.
func MetaActivePathGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaActivePath, v))
}

// MetaActivePathGTE applies the GTE predicate on the "meta_active_path" field.
func MetaActivePathGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaActivePath, v))
}

// MetaActivePathLT applies the LT predicate on the "meta_active_path" field.
func MetaActivePathLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaActivePath, v))
}

// MetaActivePathLTE applies the LTE predicate on the "meta_active_path" field.
func MetaActivePathLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaActivePath, v))
}

// MetaActivePathContains applies the Contains predicate on the "meta_active_path" field.
func MetaActivePathContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldMetaActivePath, v))
}

// MetaActivePathHasPrefix applies the HasPrefix predicate on the "meta_active_path" field.
func MetaActivePathHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldMetaActivePath, v))
}

// MetaActivePathHasSuffix applies the HasSuffix predicate on the "meta_active_path" field.
func MetaActivePathHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldMetaActivePath, v))
}

// MetaActivePathEqualFold applies the EqualFold predicate on the "meta_active_path" field.
func MetaActivePathEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldMetaActivePath, v))
}

// MetaActivePathContainsFold applies the ContainsFold predicate on the "meta_active_path" field.
func MetaActivePathContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldMetaActivePath, v))
}

// MetaAffixTabEQ applies the EQ predicate on the "meta_affix_tab" field.
func MetaAffixTabEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaAffixTab, v))
}

// MetaAffixTabNEQ applies the NEQ predicate on the "meta_affix_tab" field.
func MetaAffixTabNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaAffixTab, v))
}

// MetaAffixTabIn applies the In predicate on the "meta_affix_tab" field.
func MetaAffixTabIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaAffixTab, vs...))
}

// MetaAffixTabNotIn applies the NotIn predicate on the "meta_affix_tab" field.
func MetaAffixTabNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaAffixTab, vs...))
}

// MetaAffixTabGT applies the GT predicate on the "meta_affix_tab" field.
func MetaAffixTabGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaAffixTab, v))
}

// MetaAffixTabGTE applies the GTE predicate on the "meta_affix_tab" field.
func MetaAffixTabGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaAffixTab, v))
}

// MetaAffixTabLT applies the LT predicate on the "meta_affix_tab" field.
func MetaAffixTabLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaAffixTab, v))
}

// MetaAffixTabLTE applies the LTE predicate on the "meta_affix_tab" field.
func MetaAffixTabLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaAffixTab, v))
}

// MetaAffixTabOrderEQ applies the EQ predicate on the "meta_affix_tab_order" field.
func MetaAffixTabOrderEQ(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaAffixTabOrder, v))
}

// MetaAffixTabOrderNEQ applies the NEQ predicate on the "meta_affix_tab_order" field.
func MetaAffixTabOrderNEQ(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaAffixTabOrder, v))
}

// MetaAffixTabOrderIn applies the In predicate on the "meta_affix_tab_order" field.
func MetaAffixTabOrderIn(vs ...int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaAffixTabOrder, vs...))
}

// MetaAffixTabOrderNotIn applies the NotIn predicate on the "meta_affix_tab_order" field.
func MetaAffixTabOrderNotIn(vs ...int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaAffixTabOrder, vs...))
}

// MetaAffixTabOrderGT applies the GT predicate on the "meta_affix_tab_order" field.
func MetaAffixTabOrderGT(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaAffixTabOrder, v))
}

// MetaAffixTabOrderGTE applies the GTE predicate on the "meta_affix_tab_order" field.
func MetaAffixTabOrderGTE(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaAffixTabOrder, v))
}

// MetaAffixTabOrderLT applies the LT predicate on the "meta_affix_tab_order" field.
func MetaAffixTabOrderLT(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaAffixTabOrder, v))
}

// MetaAffixTabOrderLTE applies the LTE predicate on the "meta_affix_tab_order" field.
func MetaAffixTabOrderLTE(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaAffixTabOrder, v))
}

// MetaIframeSrcEQ applies the EQ predicate on the "meta_iframe_src" field.
func MetaIframeSrcEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaIframeSrc, v))
}

// MetaIframeSrcNEQ applies the NEQ predicate on the "meta_iframe_src" field.
func MetaIframeSrcNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaIframeSrc, v))
}

// MetaIframeSrcIn applies the In predicate on the "meta_iframe_src" field.
func MetaIframeSrcIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaIframeSrc, vs...))
}

// MetaIframeSrcNotIn applies the NotIn predicate on the "meta_iframe_src" field.
func MetaIframeSrcNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaIframeSrc, vs...))
}

// MetaIframeSrcGT applies the GT predicate on the "meta_iframe_src" field.
func MetaIframeSrcGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaIframeSrc, v))
}

// MetaIframeSrcGTE applies the GTE predicate on the "meta_iframe_src" field.
func MetaIframeSrcGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaIframeSrc, v))
}

// MetaIframeSrcLT applies the LT predicate on the "meta_iframe_src" field.
func MetaIframeSrcLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaIframeSrc, v))
}

// MetaIframeSrcLTE applies the LTE predicate on the "meta_iframe_src" field.
func MetaIframeSrcLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaIframeSrc, v))
}

// MetaIframeSrcContains applies the Contains predicate on the "meta_iframe_src" field.
func MetaIframeSrcContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldMetaIframeSrc, v))
}

// MetaIframeSrcHasPrefix applies the HasPrefix predicate on the "meta_iframe_src" field.
func MetaIframeSrcHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldMetaIframeSrc, v))
}

// MetaIframeSrcHasSuffix applies the HasSuffix predicate on the "meta_iframe_src" field.
func MetaIframeSrcHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldMetaIframeSrc, v))
}

// MetaIframeSrcEqualFold applies the EqualFold predicate on the "meta_iframe_src" field.
func MetaIframeSrcEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldMetaIframeSrc, v))
}

// MetaIframeSrcContainsFold applies the ContainsFold predicate on the "meta_iframe_src" field.
func MetaIframeSrcContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldMetaIframeSrc, v))
}

// MetaIgnoreAccessEQ applies the EQ predicate on the "meta_ignore_access" field.
func MetaIgnoreAccessEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaIgnoreAccess, v))
}

// MetaIgnoreAccessNEQ applies the NEQ predicate on the "meta_ignore_access" field.
func MetaIgnoreAccessNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaIgnoreAccess, v))
}

// MetaIgnoreAccessIn applies the In predicate on the "meta_ignore_access" field.
func MetaIgnoreAccessIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaIgnoreAccess, vs...))
}

// MetaIgnoreAccessNotIn applies the NotIn predicate on the "meta_ignore_access" field.
func MetaIgnoreAccessNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaIgnoreAccess, vs...))
}

// MetaIgnoreAccessGT applies the GT predicate on the "meta_ignore_access" field.
func MetaIgnoreAccessGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaIgnoreAccess, v))
}

// MetaIgnoreAccessGTE applies the GTE predicate on the "meta_ignore_access" field.
func MetaIgnoreAccessGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaIgnoreAccess, v))
}

// MetaIgnoreAccessLT applies the LT predicate on the "meta_ignore_access" field.
func MetaIgnoreAccessLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaIgnoreAccess, v))
}

// MetaIgnoreAccessLTE applies the LTE predicate on the "meta_ignore_access" field.
func MetaIgnoreAccessLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaIgnoreAccess, v))
}

// MetaLinkEQ applies the EQ predicate on the "meta_link" field.
func MetaLinkEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaLink, v))
}

// MetaLinkNEQ applies the NEQ predicate on the "meta_link" field.
func MetaLinkNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaLink, v))
}

// MetaLinkIn applies the In predicate on the "meta_link" field.
func MetaLinkIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaLink, vs...))
}

// MetaLinkNotIn applies the NotIn predicate on the "meta_link" field.
func MetaLinkNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaLink, vs...))
}

// MetaLinkGT applies the GT predicate on the "meta_link" field.
func MetaLinkGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaLink, v))
}

// MetaLinkGTE applies the GTE predicate on the "meta_link" field.
func MetaLinkGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaLink, v))
}

// MetaLinkLT applies the LT predicate on the "meta_link" field.
func MetaLinkLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaLink, v))
}

// MetaLinkLTE applies the LTE predicate on the "meta_link" field.
func MetaLinkLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaLink, v))
}

// MetaLinkContains applies the Contains predicate on the "meta_link" field.
func MetaLinkContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldMetaLink, v))
}

// MetaLinkHasPrefix applies the HasPrefix predicate on the "meta_link" field.
func MetaLinkHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldMetaLink, v))
}

// MetaLinkHasSuffix applies the HasSuffix predicate on the "meta_link" field.
func MetaLinkHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldMetaLink, v))
}

// MetaLinkEqualFold applies the EqualFold predicate on the "meta_link" field.
func MetaLinkEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldMetaLink, v))
}

// MetaLinkContainsFold applies the ContainsFold predicate on the "meta_link" field.
func MetaLinkContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldMetaLink, v))
}

// MetaMaxNumOfOpenTabEQ applies the EQ predicate on the "meta_max_num_of_open_tab" field.
func MetaMaxNumOfOpenTabEQ(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaMaxNumOfOpenTab, v))
}

// MetaMaxNumOfOpenTabNEQ applies the NEQ predicate on the "meta_max_num_of_open_tab" field.
func MetaMaxNumOfOpenTabNEQ(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaMaxNumOfOpenTab, v))
}

// MetaMaxNumOfOpenTabIn applies the In predicate on the "meta_max_num_of_open_tab" field.
func MetaMaxNumOfOpenTabIn(vs ...int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaMaxNumOfOpenTab, vs...))
}

// MetaMaxNumOfOpenTabNotIn applies the NotIn predicate on the "meta_max_num_of_open_tab" field.
func MetaMaxNumOfOpenTabNotIn(vs ...int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaMaxNumOfOpenTab, vs...))
}

// MetaMaxNumOfOpenTabGT applies the GT predicate on the "meta_max_num_of_open_tab" field.
func MetaMaxNumOfOpenTabGT(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaMaxNumOfOpenTab, v))
}

// MetaMaxNumOfOpenTabGTE applies the GTE predicate on the "meta_max_num_of_open_tab" field.
func MetaMaxNumOfOpenTabGTE(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaMaxNumOfOpenTab, v))
}

// MetaMaxNumOfOpenTabLT applies the LT predicate on the "meta_max_num_of_open_tab" field.
func MetaMaxNumOfOpenTabLT(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaMaxNumOfOpenTab, v))
}

// MetaMaxNumOfOpenTabLTE applies the LTE predicate on the "meta_max_num_of_open_tab" field.
func MetaMaxNumOfOpenTabLTE(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaMaxNumOfOpenTab, v))
}

// MetaMenuVisibleWithForbiddenEQ applies the EQ predicate on the "meta_menu_visible_with_forbidden" field.
func MetaMenuVisibleWithForbiddenEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaMenuVisibleWithForbidden, v))
}

// MetaMenuVisibleWithForbiddenNEQ applies the NEQ predicate on the "meta_menu_visible_with_forbidden" field.
func MetaMenuVisibleWithForbiddenNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaMenuVisibleWithForbidden, v))
}

// MetaMenuVisibleWithForbiddenIn applies the In predicate on the "meta_menu_visible_with_forbidden" field.
func MetaMenuVisibleWithForbiddenIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaMenuVisibleWithForbidden, vs...))
}

// MetaMenuVisibleWithForbiddenNotIn applies the NotIn predicate on the "meta_menu_visible_with_forbidden" field.
func MetaMenuVisibleWithForbiddenNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaMenuVisibleWithForbidden, vs...))
}

// MetaMenuVisibleWithForbiddenGT applies the GT predicate on the "meta_menu_visible_with_forbidden" field.
func MetaMenuVisibleWithForbiddenGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaMenuVisibleWithForbidden, v))
}

// MetaMenuVisibleWithForbiddenGTE applies the GTE predicate on the "meta_menu_visible_with_forbidden" field.
func MetaMenuVisibleWithForbiddenGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaMenuVisibleWithForbidden, v))
}

// MetaMenuVisibleWithForbiddenLT applies the LT predicate on the "meta_menu_visible_with_forbidden" field.
func MetaMenuVisibleWithForbiddenLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaMenuVisibleWithForbidden, v))
}

// MetaMenuVisibleWithForbiddenLTE applies the LTE predicate on the "meta_menu_visible_with_forbidden" field.
func MetaMenuVisibleWithForbiddenLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaMenuVisibleWithForbidden, v))
}

// MetaOpenInNewWindowEQ applies the EQ predicate on the "meta_open_in_new_window" field.
func MetaOpenInNewWindowEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaOpenInNewWindow, v))
}

// MetaOpenInNewWindowNEQ applies the NEQ predicate on the "meta_open_in_new_window" field.
func MetaOpenInNewWindowNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaOpenInNewWindow, v))
}

// MetaOpenInNewWindowIn applies the In predicate on the "meta_open_in_new_window" field.
func MetaOpenInNewWindowIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaOpenInNewWindow, vs...))
}

// MetaOpenInNewWindowNotIn applies the NotIn predicate on the "meta_open_in_new_window" field.
func MetaOpenInNewWindowNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaOpenInNewWindow, vs...))
}

// MetaOpenInNewWindowGT applies the GT predicate on the "meta_open_in_new_window" field.
func MetaOpenInNewWindowGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaOpenInNewWindow, v))
}

// MetaOpenInNewWindowGTE applies the GTE predicate on the "meta_open_in_new_window" field.
func MetaOpenInNewWindowGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaOpenInNewWindow, v))
}

// MetaOpenInNewWindowLT applies the LT predicate on the "meta_open_in_new_window" field.
func MetaOpenInNewWindowLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaOpenInNewWindow, v))
}

// MetaOpenInNewWindowLTE applies the LTE predicate on the "meta_open_in_new_window" field.
func MetaOpenInNewWindowLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaOpenInNewWindow, v))
}

// MetaOrderEQ applies the EQ predicate on the "meta_order" field.
func MetaOrderEQ(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaOrder, v))
}

// MetaOrderNEQ applies the NEQ predicate on the "meta_order" field.
func MetaOrderNEQ(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaOrder, v))
}

// MetaOrderIn applies the In predicate on the "meta_order" field.
func MetaOrderIn(vs ...int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaOrder, vs...))
}

// MetaOrderNotIn applies the NotIn predicate on the "meta_order" field.
func MetaOrderNotIn(vs ...int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaOrder, vs...))
}

// MetaOrderGT applies the GT predicate on the "meta_order" field.
func MetaOrderGT(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaOrder, v))
}

// MetaOrderGTE applies the GTE predicate on the "meta_order" field.
func MetaOrderGTE(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaOrder, v))
}

// MetaOrderLT applies the LT predicate on the "meta_order" field.
func MetaOrderLT(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaOrder, v))
}

// MetaOrderLTE applies the LTE predicate on the "meta_order" field.
func MetaOrderLTE(v int) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaOrder, v))
}

// MetaQueryEQ applies the EQ predicate on the "meta_query" field.
func MetaQueryEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaQuery, v))
}

// MetaQueryNEQ applies the NEQ predicate on the "meta_query" field.
func MetaQueryNEQ(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaQuery, v))
}

// MetaQueryIn applies the In predicate on the "meta_query" field.
func MetaQueryIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaQuery, vs...))
}

// MetaQueryNotIn applies the NotIn predicate on the "meta_query" field.
func MetaQueryNotIn(vs ...string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaQuery, vs...))
}

// MetaQueryGT applies the GT predicate on the "meta_query" field.
func MetaQueryGT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaQuery, v))
}

// MetaQueryGTE applies the GTE predicate on the "meta_query" field.
func MetaQueryGTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaQuery, v))
}

// MetaQueryLT applies the LT predicate on the "meta_query" field.
func MetaQueryLT(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaQuery, v))
}

// MetaQueryLTE applies the LTE predicate on the "meta_query" field.
func MetaQueryLTE(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaQuery, v))
}

// MetaQueryContains applies the Contains predicate on the "meta_query" field.
func MetaQueryContains(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContains(FieldMetaQuery, v))
}

// MetaQueryHasPrefix applies the HasPrefix predicate on the "meta_query" field.
func MetaQueryHasPrefix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasPrefix(FieldMetaQuery, v))
}

// MetaQueryHasSuffix applies the HasSuffix predicate on the "meta_query" field.
func MetaQueryHasSuffix(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldHasSuffix(FieldMetaQuery, v))
}

// MetaQueryEqualFold applies the EqualFold predicate on the "meta_query" field.
func MetaQueryEqualFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEqualFold(FieldMetaQuery, v))
}

// MetaQueryContainsFold applies the ContainsFold predicate on the "meta_query" field.
func MetaQueryContainsFold(v string) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldContainsFold(FieldMetaQuery, v))
}

// MetaNoBasicLayoutEQ applies the EQ predicate on the "meta_no_basic_layout" field.
func MetaNoBasicLayoutEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldEQ(FieldMetaNoBasicLayout, v))
}

// MetaNoBasicLayoutNEQ applies the NEQ predicate on the "meta_no_basic_layout" field.
func MetaNoBasicLayoutNEQ(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNEQ(FieldMetaNoBasicLayout, v))
}

// MetaNoBasicLayoutIn applies the In predicate on the "meta_no_basic_layout" field.
func MetaNoBasicLayoutIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldIn(FieldMetaNoBasicLayout, vs...))
}

// MetaNoBasicLayoutNotIn applies the NotIn predicate on the "meta_no_basic_layout" field.
func MetaNoBasicLayoutNotIn(vs ...int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldNotIn(FieldMetaNoBasicLayout, vs...))
}

// MetaNoBasicLayoutGT applies the GT predicate on the "meta_no_basic_layout" field.
func MetaNoBasicLayoutGT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGT(FieldMetaNoBasicLayout, v))
}

// MetaNoBasicLayoutGTE applies the GTE predicate on the "meta_no_basic_layout" field.
func MetaNoBasicLayoutGTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldGTE(FieldMetaNoBasicLayout, v))
}

// MetaNoBasicLayoutLT applies the LT predicate on the "meta_no_basic_layout" field.
func MetaNoBasicLayoutLT(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLT(FieldMetaNoBasicLayout, v))
}

// MetaNoBasicLayoutLTE applies the LTE predicate on the "meta_no_basic_layout" field.
func MetaNoBasicLayoutLTE(v int8) predicate.SysMenu {
	return predicate.SysMenu(sql.FieldLTE(FieldMetaNoBasicLayout, v))
}

// HasSysRoles applies the HasEdge predicate on the "sysRoles" edge.
func HasSysRoles() predicate.SysMenu {
	return predicate.SysMenu(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, SysRolesTable, SysRolesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSysRolesWith applies the HasEdge predicate on the "sysRoles" edge with a given conditions (other predicates).
func HasSysRolesWith(preds ...predicate.SysRole) predicate.SysMenu {
	return predicate.SysMenu(func(s *sql.Selector) {
		step := newSysRolesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.SysMenu {
	return predicate.SysMenu(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.SysMenu) predicate.SysMenu {
	return predicate.SysMenu(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.SysMenu {
	return predicate.SysMenu(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.SysMenu) predicate.SysMenu {
	return predicate.SysMenu(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysMenu) predicate.SysMenu {
	return predicate.SysMenu(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysMenu) predicate.SysMenu {
	return predicate.SysMenu(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysMenu) predicate.SysMenu {
	return predicate.SysMenu(sql.NotPredicates(p))
}
