// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"go-ent-demo/entcore/sysdept"
	"go-ent-demo/entcore/sysmenu"
	"go-ent-demo/entcore/sysrole"
	"go-ent-demo/entcore/sysuser"
	"go-ent-demo/schema"
	"go-ent-demo/types"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sysdeptMixin := schema.SysDept{}.Mixin()
	sysdeptMixinHooks8 := sysdeptMixin[8].Hooks()
	sysdept.Hooks[0] = sysdeptMixinHooks8[0]
	sysdeptMixinInters8 := sysdeptMixin[8].Interceptors()
	sysdept.Interceptors[0] = sysdeptMixinInters8[0]
	sysdeptMixinFields0 := sysdeptMixin[0].Fields()
	_ = sysdeptMixinFields0
	sysdeptMixinFields2 := sysdeptMixin[2].Fields()
	_ = sysdeptMixinFields2
	sysdeptMixinFields3 := sysdeptMixin[3].Fields()
	_ = sysdeptMixinFields3
	sysdeptMixinFields4 := sysdeptMixin[4].Fields()
	_ = sysdeptMixinFields4
	sysdeptMixinFields5 := sysdeptMixin[5].Fields()
	_ = sysdeptMixinFields5
	sysdeptMixinFields8 := sysdeptMixin[8].Fields()
	_ = sysdeptMixinFields8
	sysdeptFields := schema.SysDept{}.Fields()
	_ = sysdeptFields
	// sysdeptDescSort is the schema descriptor for sort field.
	sysdeptDescSort := sysdeptMixinFields2[0].Descriptor()
	// sysdept.DefaultSort holds the default value on creation for the sort field.
	sysdept.DefaultSort = sysdeptDescSort.Default.(int)
	// sysdeptDescStatus is the schema descriptor for status field.
	sysdeptDescStatus := sysdeptMixinFields3[0].Descriptor()
	// sysdept.DefaultStatus holds the default value on creation for the status field.
	sysdept.DefaultStatus = sysdeptDescStatus.Default.(string)
	// sysdeptDescCreatedAt is the schema descriptor for created_at field.
	sysdeptDescCreatedAt := sysdeptMixinFields4[1].Descriptor()
	// sysdept.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysdept.DefaultCreatedAt = sysdeptDescCreatedAt.Default.(func() types.CustomTime)
	// sysdept.UpdateDefaultCreatedAt holds the default value on update for the created_at field.
	sysdept.UpdateDefaultCreatedAt = sysdeptDescCreatedAt.UpdateDefault.(func() types.CustomTime)
	// sysdeptDescUpdatedAt is the schema descriptor for updated_at field.
	sysdeptDescUpdatedAt := sysdeptMixinFields5[1].Descriptor()
	// sysdept.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysdept.DefaultUpdatedAt = sysdeptDescUpdatedAt.Default.(func() types.CustomTime)
	// sysdept.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysdept.UpdateDefaultUpdatedAt = sysdeptDescUpdatedAt.UpdateDefault.(func() types.CustomTime)
	// sysdeptDescDelFlag is the schema descriptor for del_flag field.
	sysdeptDescDelFlag := sysdeptMixinFields8[0].Descriptor()
	// sysdept.DefaultDelFlag holds the default value on creation for the del_flag field.
	sysdept.DefaultDelFlag = sysdeptDescDelFlag.Default.(int8)
	// sysdeptDescID is the schema descriptor for id field.
	sysdeptDescID := sysdeptMixinFields0[0].Descriptor()
	// sysdept.DefaultID holds the default value on creation for the id field.
	sysdept.DefaultID = sysdeptDescID.Default.(func() types.ID)
	sysmenuMixin := schema.SysMenu{}.Mixin()
	sysmenuMixinHooks8 := sysmenuMixin[8].Hooks()
	sysmenu.Hooks[0] = sysmenuMixinHooks8[0]
	sysmenuMixinInters8 := sysmenuMixin[8].Interceptors()
	sysmenu.Interceptors[0] = sysmenuMixinInters8[0]
	sysmenuMixinFields0 := sysmenuMixin[0].Fields()
	_ = sysmenuMixinFields0
	sysmenuMixinFields2 := sysmenuMixin[2].Fields()
	_ = sysmenuMixinFields2
	sysmenuMixinFields3 := sysmenuMixin[3].Fields()
	_ = sysmenuMixinFields3
	sysmenuMixinFields4 := sysmenuMixin[4].Fields()
	_ = sysmenuMixinFields4
	sysmenuMixinFields5 := sysmenuMixin[5].Fields()
	_ = sysmenuMixinFields5
	sysmenuMixinFields8 := sysmenuMixin[8].Fields()
	_ = sysmenuMixinFields8
	sysmenuFields := schema.SysMenu{}.Fields()
	_ = sysmenuFields
	// sysmenuDescSort is the schema descriptor for sort field.
	sysmenuDescSort := sysmenuMixinFields2[0].Descriptor()
	// sysmenu.DefaultSort holds the default value on creation for the sort field.
	sysmenu.DefaultSort = sysmenuDescSort.Default.(int)
	// sysmenuDescStatus is the schema descriptor for status field.
	sysmenuDescStatus := sysmenuMixinFields3[0].Descriptor()
	// sysmenu.DefaultStatus holds the default value on creation for the status field.
	sysmenu.DefaultStatus = sysmenuDescStatus.Default.(string)
	// sysmenuDescCreatedAt is the schema descriptor for created_at field.
	sysmenuDescCreatedAt := sysmenuMixinFields4[1].Descriptor()
	// sysmenu.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysmenu.DefaultCreatedAt = sysmenuDescCreatedAt.Default.(func() types.CustomTime)
	// sysmenu.UpdateDefaultCreatedAt holds the default value on update for the created_at field.
	sysmenu.UpdateDefaultCreatedAt = sysmenuDescCreatedAt.UpdateDefault.(func() types.CustomTime)
	// sysmenuDescUpdatedAt is the schema descriptor for updated_at field.
	sysmenuDescUpdatedAt := sysmenuMixinFields5[1].Descriptor()
	// sysmenu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysmenu.DefaultUpdatedAt = sysmenuDescUpdatedAt.Default.(func() types.CustomTime)
	// sysmenu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysmenu.UpdateDefaultUpdatedAt = sysmenuDescUpdatedAt.UpdateDefault.(func() types.CustomTime)
	// sysmenuDescDelFlag is the schema descriptor for del_flag field.
	sysmenuDescDelFlag := sysmenuMixinFields8[0].Descriptor()
	// sysmenu.DefaultDelFlag holds the default value on creation for the del_flag field.
	sysmenu.DefaultDelFlag = sysmenuDescDelFlag.Default.(int8)
	// sysmenuDescComponent is the schema descriptor for component field.
	sysmenuDescComponent := sysmenuFields[3].Descriptor()
	// sysmenu.DefaultComponent holds the default value on creation for the component field.
	sysmenu.DefaultComponent = sysmenuDescComponent.Default.(string)
	// sysmenuDescPermission is the schema descriptor for permission field.
	sysmenuDescPermission := sysmenuFields[4].Descriptor()
	// sysmenu.DefaultPermission holds the default value on creation for the permission field.
	sysmenu.DefaultPermission = sysmenuDescPermission.Default.(string)
	// sysmenuDescRedirect is the schema descriptor for redirect field.
	sysmenuDescRedirect := sysmenuFields[5].Descriptor()
	// sysmenu.DefaultRedirect holds the default value on creation for the redirect field.
	sysmenu.DefaultRedirect = sysmenuDescRedirect.Default.(string)
	// sysmenuDescMetaIcon is the schema descriptor for meta_icon field.
	sysmenuDescMetaIcon := sysmenuFields[7].Descriptor()
	// sysmenu.DefaultMetaIcon holds the default value on creation for the meta_icon field.
	sysmenu.DefaultMetaIcon = sysmenuDescMetaIcon.Default.(string)
	// sysmenuDescMetaActiveIcon is the schema descriptor for meta_active_icon field.
	sysmenuDescMetaActiveIcon := sysmenuFields[8].Descriptor()
	// sysmenu.DefaultMetaActiveIcon holds the default value on creation for the meta_active_icon field.
	sysmenu.DefaultMetaActiveIcon = sysmenuDescMetaActiveIcon.Default.(string)
	// sysmenuDescMetaKeepAlive is the schema descriptor for meta_keep_alive field.
	sysmenuDescMetaKeepAlive := sysmenuFields[9].Descriptor()
	// sysmenu.DefaultMetaKeepAlive holds the default value on creation for the meta_keep_alive field.
	sysmenu.DefaultMetaKeepAlive = sysmenuDescMetaKeepAlive.Default.(int8)
	// sysmenuDescMetaHideInMenu is the schema descriptor for meta_hide_in_menu field.
	sysmenuDescMetaHideInMenu := sysmenuFields[10].Descriptor()
	// sysmenu.DefaultMetaHideInMenu holds the default value on creation for the meta_hide_in_menu field.
	sysmenu.DefaultMetaHideInMenu = sysmenuDescMetaHideInMenu.Default.(int8)
	// sysmenuDescMetaHideInTab is the schema descriptor for meta_hide_in_tab field.
	sysmenuDescMetaHideInTab := sysmenuFields[11].Descriptor()
	// sysmenu.DefaultMetaHideInTab holds the default value on creation for the meta_hide_in_tab field.
	sysmenu.DefaultMetaHideInTab = sysmenuDescMetaHideInTab.Default.(int8)
	// sysmenuDescMetaHideInBreadcrumb is the schema descriptor for meta_hide_in_breadcrumb field.
	sysmenuDescMetaHideInBreadcrumb := sysmenuFields[12].Descriptor()
	// sysmenu.DefaultMetaHideInBreadcrumb holds the default value on creation for the meta_hide_in_breadcrumb field.
	sysmenu.DefaultMetaHideInBreadcrumb = sysmenuDescMetaHideInBreadcrumb.Default.(int8)
	// sysmenuDescMetaHideChildrenInMenu is the schema descriptor for meta_hide_children_in_menu field.
	sysmenuDescMetaHideChildrenInMenu := sysmenuFields[13].Descriptor()
	// sysmenu.DefaultMetaHideChildrenInMenu holds the default value on creation for the meta_hide_children_in_menu field.
	sysmenu.DefaultMetaHideChildrenInMenu = sysmenuDescMetaHideChildrenInMenu.Default.(int8)
	// sysmenuDescMetaAuthority is the schema descriptor for meta_authority field.
	sysmenuDescMetaAuthority := sysmenuFields[14].Descriptor()
	// sysmenu.DefaultMetaAuthority holds the default value on creation for the meta_authority field.
	sysmenu.DefaultMetaAuthority = sysmenuDescMetaAuthority.Default.(string)
	// sysmenuDescMetaBadge is the schema descriptor for meta_badge field.
	sysmenuDescMetaBadge := sysmenuFields[15].Descriptor()
	// sysmenu.DefaultMetaBadge holds the default value on creation for the meta_badge field.
	sysmenu.DefaultMetaBadge = sysmenuDescMetaBadge.Default.(string)
	// sysmenuDescMetaBadgeType is the schema descriptor for meta_badge_type field.
	sysmenuDescMetaBadgeType := sysmenuFields[16].Descriptor()
	// sysmenu.DefaultMetaBadgeType holds the default value on creation for the meta_badge_type field.
	sysmenu.DefaultMetaBadgeType = sysmenuDescMetaBadgeType.Default.(int8)
	// sysmenuDescMetaBadgeVariants is the schema descriptor for meta_badge_variants field.
	sysmenuDescMetaBadgeVariants := sysmenuFields[17].Descriptor()
	// sysmenu.DefaultMetaBadgeVariants holds the default value on creation for the meta_badge_variants field.
	sysmenu.DefaultMetaBadgeVariants = sysmenuDescMetaBadgeVariants.Default.(int8)
	// sysmenuDescMetaFullPathKey is the schema descriptor for meta_full_path_key field.
	sysmenuDescMetaFullPathKey := sysmenuFields[18].Descriptor()
	// sysmenu.DefaultMetaFullPathKey holds the default value on creation for the meta_full_path_key field.
	sysmenu.DefaultMetaFullPathKey = sysmenuDescMetaFullPathKey.Default.(int8)
	// sysmenuDescMetaActivePath is the schema descriptor for meta_active_path field.
	sysmenuDescMetaActivePath := sysmenuFields[19].Descriptor()
	// sysmenu.DefaultMetaActivePath holds the default value on creation for the meta_active_path field.
	sysmenu.DefaultMetaActivePath = sysmenuDescMetaActivePath.Default.(string)
	// sysmenuDescMetaAffixTab is the schema descriptor for meta_affix_tab field.
	sysmenuDescMetaAffixTab := sysmenuFields[20].Descriptor()
	// sysmenu.DefaultMetaAffixTab holds the default value on creation for the meta_affix_tab field.
	sysmenu.DefaultMetaAffixTab = sysmenuDescMetaAffixTab.Default.(int8)
	// sysmenuDescMetaAffixTabOrder is the schema descriptor for meta_affix_tab_order field.
	sysmenuDescMetaAffixTabOrder := sysmenuFields[21].Descriptor()
	// sysmenu.DefaultMetaAffixTabOrder holds the default value on creation for the meta_affix_tab_order field.
	sysmenu.DefaultMetaAffixTabOrder = sysmenuDescMetaAffixTabOrder.Default.(int)
	// sysmenuDescMetaIframeSrc is the schema descriptor for meta_iframe_src field.
	sysmenuDescMetaIframeSrc := sysmenuFields[22].Descriptor()
	// sysmenu.DefaultMetaIframeSrc holds the default value on creation for the meta_iframe_src field.
	sysmenu.DefaultMetaIframeSrc = sysmenuDescMetaIframeSrc.Default.(string)
	// sysmenuDescMetaIgnoreAccess is the schema descriptor for meta_ignore_access field.
	sysmenuDescMetaIgnoreAccess := sysmenuFields[23].Descriptor()
	// sysmenu.DefaultMetaIgnoreAccess holds the default value on creation for the meta_ignore_access field.
	sysmenu.DefaultMetaIgnoreAccess = sysmenuDescMetaIgnoreAccess.Default.(int8)
	// sysmenuDescMetaLink is the schema descriptor for meta_link field.
	sysmenuDescMetaLink := sysmenuFields[24].Descriptor()
	// sysmenu.DefaultMetaLink holds the default value on creation for the meta_link field.
	sysmenu.DefaultMetaLink = sysmenuDescMetaLink.Default.(string)
	// sysmenuDescMetaMaxNumOfOpenTab is the schema descriptor for meta_max_num_of_open_tab field.
	sysmenuDescMetaMaxNumOfOpenTab := sysmenuFields[25].Descriptor()
	// sysmenu.DefaultMetaMaxNumOfOpenTab holds the default value on creation for the meta_max_num_of_open_tab field.
	sysmenu.DefaultMetaMaxNumOfOpenTab = sysmenuDescMetaMaxNumOfOpenTab.Default.(int)
	// sysmenuDescMetaMenuVisibleWithForbidden is the schema descriptor for meta_menu_visible_with_forbidden field.
	sysmenuDescMetaMenuVisibleWithForbidden := sysmenuFields[26].Descriptor()
	// sysmenu.DefaultMetaMenuVisibleWithForbidden holds the default value on creation for the meta_menu_visible_with_forbidden field.
	sysmenu.DefaultMetaMenuVisibleWithForbidden = sysmenuDescMetaMenuVisibleWithForbidden.Default.(int8)
	// sysmenuDescMetaOpenInNewWindow is the schema descriptor for meta_open_in_new_window field.
	sysmenuDescMetaOpenInNewWindow := sysmenuFields[27].Descriptor()
	// sysmenu.DefaultMetaOpenInNewWindow holds the default value on creation for the meta_open_in_new_window field.
	sysmenu.DefaultMetaOpenInNewWindow = sysmenuDescMetaOpenInNewWindow.Default.(int8)
	// sysmenuDescMetaOrder is the schema descriptor for meta_order field.
	sysmenuDescMetaOrder := sysmenuFields[28].Descriptor()
	// sysmenu.DefaultMetaOrder holds the default value on creation for the meta_order field.
	sysmenu.DefaultMetaOrder = sysmenuDescMetaOrder.Default.(int)
	// sysmenuDescMetaQuery is the schema descriptor for meta_query field.
	sysmenuDescMetaQuery := sysmenuFields[29].Descriptor()
	// sysmenu.DefaultMetaQuery holds the default value on creation for the meta_query field.
	sysmenu.DefaultMetaQuery = sysmenuDescMetaQuery.Default.(string)
	// sysmenuDescMetaNoBasicLayout is the schema descriptor for meta_no_basic_layout field.
	sysmenuDescMetaNoBasicLayout := sysmenuFields[30].Descriptor()
	// sysmenu.DefaultMetaNoBasicLayout holds the default value on creation for the meta_no_basic_layout field.
	sysmenu.DefaultMetaNoBasicLayout = sysmenuDescMetaNoBasicLayout.Default.(int8)
	// sysmenuDescID is the schema descriptor for id field.
	sysmenuDescID := sysmenuMixinFields0[0].Descriptor()
	// sysmenu.DefaultID holds the default value on creation for the id field.
	sysmenu.DefaultID = sysmenuDescID.Default.(func() types.ID)
	sysroleMixin := schema.SysRole{}.Mixin()
	sysroleMixinHooks7 := sysroleMixin[7].Hooks()
	sysrole.Hooks[0] = sysroleMixinHooks7[0]
	sysroleMixinInters7 := sysroleMixin[7].Interceptors()
	sysrole.Interceptors[0] = sysroleMixinInters7[0]
	sysroleMixinFields0 := sysroleMixin[0].Fields()
	_ = sysroleMixinFields0
	sysroleMixinFields1 := sysroleMixin[1].Fields()
	_ = sysroleMixinFields1
	sysroleMixinFields2 := sysroleMixin[2].Fields()
	_ = sysroleMixinFields2
	sysroleMixinFields3 := sysroleMixin[3].Fields()
	_ = sysroleMixinFields3
	sysroleMixinFields4 := sysroleMixin[4].Fields()
	_ = sysroleMixinFields4
	sysroleMixinFields7 := sysroleMixin[7].Fields()
	_ = sysroleMixinFields7
	sysroleFields := schema.SysRole{}.Fields()
	_ = sysroleFields
	// sysroleDescSort is the schema descriptor for sort field.
	sysroleDescSort := sysroleMixinFields1[0].Descriptor()
	// sysrole.DefaultSort holds the default value on creation for the sort field.
	sysrole.DefaultSort = sysroleDescSort.Default.(int)
	// sysroleDescStatus is the schema descriptor for status field.
	sysroleDescStatus := sysroleMixinFields2[0].Descriptor()
	// sysrole.DefaultStatus holds the default value on creation for the status field.
	sysrole.DefaultStatus = sysroleDescStatus.Default.(string)
	// sysroleDescCreatedAt is the schema descriptor for created_at field.
	sysroleDescCreatedAt := sysroleMixinFields3[1].Descriptor()
	// sysrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysrole.DefaultCreatedAt = sysroleDescCreatedAt.Default.(func() types.CustomTime)
	// sysrole.UpdateDefaultCreatedAt holds the default value on update for the created_at field.
	sysrole.UpdateDefaultCreatedAt = sysroleDescCreatedAt.UpdateDefault.(func() types.CustomTime)
	// sysroleDescUpdatedAt is the schema descriptor for updated_at field.
	sysroleDescUpdatedAt := sysroleMixinFields4[1].Descriptor()
	// sysrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysrole.DefaultUpdatedAt = sysroleDescUpdatedAt.Default.(func() types.CustomTime)
	// sysrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysrole.UpdateDefaultUpdatedAt = sysroleDescUpdatedAt.UpdateDefault.(func() types.CustomTime)
	// sysroleDescDelFlag is the schema descriptor for del_flag field.
	sysroleDescDelFlag := sysroleMixinFields7[0].Descriptor()
	// sysrole.DefaultDelFlag holds the default value on creation for the del_flag field.
	sysrole.DefaultDelFlag = sysroleDescDelFlag.Default.(int8)
	// sysroleDescID is the schema descriptor for id field.
	sysroleDescID := sysroleMixinFields0[0].Descriptor()
	// sysrole.DefaultID holds the default value on creation for the id field.
	sysrole.DefaultID = sysroleDescID.Default.(func() types.ID)
	sysuserMixin := schema.SysUser{}.Mixin()
	sysuserMixinHooks5 := sysuserMixin[5].Hooks()
	sysuser.Hooks[0] = sysuserMixinHooks5[0]
	sysuserMixinInters5 := sysuserMixin[5].Interceptors()
	sysuser.Interceptors[0] = sysuserMixinInters5[0]
	sysuserMixinFields0 := sysuserMixin[0].Fields()
	_ = sysuserMixinFields0
	sysuserMixinFields1 := sysuserMixin[1].Fields()
	_ = sysuserMixinFields1
	sysuserMixinFields2 := sysuserMixin[2].Fields()
	_ = sysuserMixinFields2
	sysuserMixinFields5 := sysuserMixin[5].Fields()
	_ = sysuserMixinFields5
	sysuserFields := schema.SysUser{}.Fields()
	_ = sysuserFields
	// sysuserDescCreatedAt is the schema descriptor for created_at field.
	sysuserDescCreatedAt := sysuserMixinFields1[1].Descriptor()
	// sysuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysuser.DefaultCreatedAt = sysuserDescCreatedAt.Default.(func() types.CustomTime)
	// sysuser.UpdateDefaultCreatedAt holds the default value on update for the created_at field.
	sysuser.UpdateDefaultCreatedAt = sysuserDescCreatedAt.UpdateDefault.(func() types.CustomTime)
	// sysuserDescUpdatedAt is the schema descriptor for updated_at field.
	sysuserDescUpdatedAt := sysuserMixinFields2[1].Descriptor()
	// sysuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysuser.DefaultUpdatedAt = sysuserDescUpdatedAt.Default.(func() types.CustomTime)
	// sysuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sysuser.UpdateDefaultUpdatedAt = sysuserDescUpdatedAt.UpdateDefault.(func() types.CustomTime)
	// sysuserDescDelFlag is the schema descriptor for del_flag field.
	sysuserDescDelFlag := sysuserMixinFields5[0].Descriptor()
	// sysuser.DefaultDelFlag holds the default value on creation for the del_flag field.
	sysuser.DefaultDelFlag = sysuserDescDelFlag.Default.(int8)
	// sysuserDescID is the schema descriptor for id field.
	sysuserDescID := sysuserMixinFields0[0].Descriptor()
	// sysuser.DefaultID holds the default value on creation for the id field.
	sysuser.DefaultID = sysuserDescID.Default.(func() types.ID)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
