// Code generated by ent, DO NOT EDIT.

package sysrole

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sysrole type in the database.
	Label = "sys_role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoleName holds the string denoting the role_name field in the database.
	FieldRoleName = "role_name"
	// FieldRoleCode holds the string denoting the role_code field in the database.
	FieldRoleCode = "role_code"
	// EdgeSysUsers holds the string denoting the sys_users edge name in mutations.
	EdgeSysUsers = "sys_users"
	// Table holds the table name of the sysrole in the database.
	Table = "sys_role"
	// SysUsersTable is the table that holds the sys_users relation/edge. The primary key declared below.
	SysUsersTable = "sys_user_role"
	// SysUsersInverseTable is the table name for the SysUser entity.
	// It exists in this package in order to avoid circular dependency with the "sysuser" package.
	SysUsersInverseTable = "sys_user"
)

// Columns holds all SQL columns for sysrole fields.
var Columns = []string{
	FieldID,
	FieldRoleName,
	FieldRoleCode,
}

var (
	// SysUsersPrimaryKey and SysUsersColumn2 are the table columns denoting the
	// primary key for the sys_users relation (M2M).
	SysUsersPrimaryKey = []string{"user_id", "role_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the SysRole queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRoleName orders the results by the role_name field.
func ByRoleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleName, opts...).ToFunc()
}

// ByRoleCode orders the results by the role_code field.
func ByRoleCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleCode, opts...).ToFunc()
}

// BySysUsersCount orders the results by sys_users count.
func BySysUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSysUsersStep(), opts...)
	}
}

// BySysUsers orders the results by sys_users terms.
func BySysUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSysUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSysUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SysUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, SysUsersTable, SysUsersPrimaryKey...),
	)
}
