// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-ent-demo/ent/dept"
	"go-ent-demo/ent/predicate"
	"go-ent-demo/ent/role"
	"go-ent-demo/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoleUpdate is the builder for updating Role entities.
type RoleUpdate struct {
	config
	hooks    []Hook
	mutation *RoleMutation
}

// Where appends a list predicates to the RoleUpdate builder.
func (_u *RoleUpdate) Where(ps ...predicate.Role) *RoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoleName sets the "role_name" field.
func (_u *RoleUpdate) SetRoleName(v string) *RoleUpdate {
	_u.mutation.SetRoleName(v)
	return _u
}

// SetNillableRoleName sets the "role_name" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableRoleName(v *string) *RoleUpdate {
	if v != nil {
		_u.SetRoleName(*v)
	}
	return _u
}

// ClearRoleName clears the value of the "role_name" field.
func (_u *RoleUpdate) ClearRoleName() *RoleUpdate {
	_u.mutation.ClearRoleName()
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *RoleUpdate) SetRoleCode(v string) *RoleUpdate {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableRoleCode(v *string) *RoleUpdate {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// ClearRoleCode clears the value of the "role_code" field.
func (_u *RoleUpdate) ClearRoleCode() *RoleUpdate {
	_u.mutation.ClearRoleCode()
	return _u
}

// AddDeptIDs adds the "depts" edge to the Dept entity by IDs.
func (_u *RoleUpdate) AddDeptIDs(ids ...int64) *RoleUpdate {
	_u.mutation.AddDeptIDs(ids...)
	return _u
}

// AddDepts adds the "depts" edges to the Dept entity.
func (_u *RoleUpdate) AddDepts(v ...*Dept) *RoleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeptIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *RoleUpdate) AddUserIDs(ids ...int64) *RoleUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *RoleUpdate) AddUsers(v ...*User) *RoleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the RoleMutation object of the builder.
func (_u *RoleUpdate) Mutation() *RoleMutation {
	return _u.mutation
}

// ClearDepts clears all "depts" edges to the Dept entity.
func (_u *RoleUpdate) ClearDepts() *RoleUpdate {
	_u.mutation.ClearDepts()
	return _u
}

// RemoveDeptIDs removes the "depts" edge to Dept entities by IDs.
func (_u *RoleUpdate) RemoveDeptIDs(ids ...int64) *RoleUpdate {
	_u.mutation.RemoveDeptIDs(ids...)
	return _u
}

// RemoveDepts removes "depts" edges to Dept entities.
func (_u *RoleUpdate) RemoveDepts(v ...*Dept) *RoleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeptIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *RoleUpdate) ClearUsers() *RoleUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *RoleUpdate) RemoveUserIDs(ids ...int64) *RoleUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *RoleUpdate) RemoveUsers(v ...*User) *RoleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoleName(); ok {
		_spec.SetField(role.FieldRoleName, field.TypeString, value)
	}
	if _u.mutation.RoleNameCleared() {
		_spec.ClearField(role.FieldRoleName, field.TypeString)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(role.FieldRoleCode, field.TypeString, value)
	}
	if _u.mutation.RoleCodeCleared() {
		_spec.ClearField(role.FieldRoleCode, field.TypeString)
	}
	if _u.mutation.DeptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.DeptsTable,
			Columns: role.DeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeptsIDs(); len(nodes) > 0 && !_u.mutation.DeptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.DeptsTable,
			Columns: role.DeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.DeptsTable,
			Columns: role.DeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.UsersTable,
			Columns: role.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.UsersTable,
			Columns: role.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.UsersTable,
			Columns: role.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoleUpdateOne is the builder for updating a single Role entity.
type RoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoleMutation
}

// SetRoleName sets the "role_name" field.
func (_u *RoleUpdateOne) SetRoleName(v string) *RoleUpdateOne {
	_u.mutation.SetRoleName(v)
	return _u
}

// SetNillableRoleName sets the "role_name" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableRoleName(v *string) *RoleUpdateOne {
	if v != nil {
		_u.SetRoleName(*v)
	}
	return _u
}

// ClearRoleName clears the value of the "role_name" field.
func (_u *RoleUpdateOne) ClearRoleName() *RoleUpdateOne {
	_u.mutation.ClearRoleName()
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *RoleUpdateOne) SetRoleCode(v string) *RoleUpdateOne {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableRoleCode(v *string) *RoleUpdateOne {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// ClearRoleCode clears the value of the "role_code" field.
func (_u *RoleUpdateOne) ClearRoleCode() *RoleUpdateOne {
	_u.mutation.ClearRoleCode()
	return _u
}

// AddDeptIDs adds the "depts" edge to the Dept entity by IDs.
func (_u *RoleUpdateOne) AddDeptIDs(ids ...int64) *RoleUpdateOne {
	_u.mutation.AddDeptIDs(ids...)
	return _u
}

// AddDepts adds the "depts" edges to the Dept entity.
func (_u *RoleUpdateOne) AddDepts(v ...*Dept) *RoleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeptIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *RoleUpdateOne) AddUserIDs(ids ...int64) *RoleUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *RoleUpdateOne) AddUsers(v ...*User) *RoleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the RoleMutation object of the builder.
func (_u *RoleUpdateOne) Mutation() *RoleMutation {
	return _u.mutation
}

// ClearDepts clears all "depts" edges to the Dept entity.
func (_u *RoleUpdateOne) ClearDepts() *RoleUpdateOne {
	_u.mutation.ClearDepts()
	return _u
}

// RemoveDeptIDs removes the "depts" edge to Dept entities by IDs.
func (_u *RoleUpdateOne) RemoveDeptIDs(ids ...int64) *RoleUpdateOne {
	_u.mutation.RemoveDeptIDs(ids...)
	return _u
}

// RemoveDepts removes "depts" edges to Dept entities.
func (_u *RoleUpdateOne) RemoveDepts(v ...*Dept) *RoleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeptIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *RoleUpdateOne) ClearUsers() *RoleUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *RoleUpdateOne) RemoveUserIDs(ids ...int64) *RoleUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *RoleUpdateOne) RemoveUsers(v ...*User) *RoleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the RoleUpdate builder.
func (_u *RoleUpdateOne) Where(ps ...predicate.Role) *RoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoleUpdateOne) Select(field string, fields ...string) *RoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Role entity.
func (_u *RoleUpdateOne) Save(ctx context.Context) (*Role, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleUpdateOne) SaveX(ctx context.Context) *Role {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RoleUpdateOne) sqlSave(ctx context.Context) (_node *Role, err error) {
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Role.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, role.FieldID)
		for _, f := range fields {
			if !role.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != role.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoleName(); ok {
		_spec.SetField(role.FieldRoleName, field.TypeString, value)
	}
	if _u.mutation.RoleNameCleared() {
		_spec.ClearField(role.FieldRoleName, field.TypeString)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(role.FieldRoleCode, field.TypeString, value)
	}
	if _u.mutation.RoleCodeCleared() {
		_spec.ClearField(role.FieldRoleCode, field.TypeString)
	}
	if _u.mutation.DeptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.DeptsTable,
			Columns: role.DeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeptsIDs(); len(nodes) > 0 && !_u.mutation.DeptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.DeptsTable,
			Columns: role.DeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.DeptsTable,
			Columns: role.DeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.UsersTable,
			Columns: role.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.UsersTable,
			Columns: role.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.UsersTable,
			Columns: role.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Role{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
