// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-ent-demo/ent/dept"
	"go-ent-demo/ent/predicate"
	"go-ent-demo/ent/role"
	"go-ent-demo/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoleUpdate is the builder for updating Role entities.
type RoleUpdate struct {
	config
	hooks    []Hook
	mutation *RoleMutation
}

// Where appends a list predicates to the RoleUpdate builder.
func (ru *RoleUpdate) Where(ps ...predicate.Role) *RoleUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetRoleName sets the "role_name" field.
func (ru *RoleUpdate) SetRoleName(s string) *RoleUpdate {
	ru.mutation.SetRoleName(s)
	return ru
}

// SetNillableRoleName sets the "role_name" field if the given value is not nil.
func (ru *RoleUpdate) SetNillableRoleName(s *string) *RoleUpdate {
	if s != nil {
		ru.SetRoleName(*s)
	}
	return ru
}

// ClearRoleName clears the value of the "role_name" field.
func (ru *RoleUpdate) ClearRoleName() *RoleUpdate {
	ru.mutation.ClearRoleName()
	return ru
}

// SetRoleCode sets the "role_code" field.
func (ru *RoleUpdate) SetRoleCode(s string) *RoleUpdate {
	ru.mutation.SetRoleCode(s)
	return ru
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (ru *RoleUpdate) SetNillableRoleCode(s *string) *RoleUpdate {
	if s != nil {
		ru.SetRoleCode(*s)
	}
	return ru
}

// ClearRoleCode clears the value of the "role_code" field.
func (ru *RoleUpdate) ClearRoleCode() *RoleUpdate {
	ru.mutation.ClearRoleCode()
	return ru
}

// AddSysDeptIDs adds the "sysDepts" edge to the Dept entity by IDs.
func (ru *RoleUpdate) AddSysDeptIDs(ids ...int64) *RoleUpdate {
	ru.mutation.AddSysDeptIDs(ids...)
	return ru
}

// AddSysDepts adds the "sysDepts" edges to the Dept entity.
func (ru *RoleUpdate) AddSysDepts(d ...*Dept) *RoleUpdate {
	ids := make([]int64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return ru.AddSysDeptIDs(ids...)
}

// AddSysUserIDs adds the "sysUsers" edge to the User entity by IDs.
func (ru *RoleUpdate) AddSysUserIDs(ids ...int64) *RoleUpdate {
	ru.mutation.AddSysUserIDs(ids...)
	return ru
}

// AddSysUsers adds the "sysUsers" edges to the User entity.
func (ru *RoleUpdate) AddSysUsers(u ...*User) *RoleUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ru.AddSysUserIDs(ids...)
}

// Mutation returns the RoleMutation object of the builder.
func (ru *RoleUpdate) Mutation() *RoleMutation {
	return ru.mutation
}

// ClearSysDepts clears all "sysDepts" edges to the Dept entity.
func (ru *RoleUpdate) ClearSysDepts() *RoleUpdate {
	ru.mutation.ClearSysDepts()
	return ru
}

// RemoveSysDeptIDs removes the "sysDepts" edge to Dept entities by IDs.
func (ru *RoleUpdate) RemoveSysDeptIDs(ids ...int64) *RoleUpdate {
	ru.mutation.RemoveSysDeptIDs(ids...)
	return ru
}

// RemoveSysDepts removes "sysDepts" edges to Dept entities.
func (ru *RoleUpdate) RemoveSysDepts(d ...*Dept) *RoleUpdate {
	ids := make([]int64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return ru.RemoveSysDeptIDs(ids...)
}

// ClearSysUsers clears all "sysUsers" edges to the User entity.
func (ru *RoleUpdate) ClearSysUsers() *RoleUpdate {
	ru.mutation.ClearSysUsers()
	return ru
}

// RemoveSysUserIDs removes the "sysUsers" edge to User entities by IDs.
func (ru *RoleUpdate) RemoveSysUserIDs(ids ...int64) *RoleUpdate {
	ru.mutation.RemoveSysUserIDs(ids...)
	return ru
}

// RemoveSysUsers removes "sysUsers" edges to User entities.
func (ru *RoleUpdate) RemoveSysUsers(u ...*User) *RoleUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ru.RemoveSysUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoleUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoleUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoleUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.RoleName(); ok {
		_spec.SetField(role.FieldRoleName, field.TypeString, value)
	}
	if ru.mutation.RoleNameCleared() {
		_spec.ClearField(role.FieldRoleName, field.TypeString)
	}
	if value, ok := ru.mutation.RoleCode(); ok {
		_spec.SetField(role.FieldRoleCode, field.TypeString, value)
	}
	if ru.mutation.RoleCodeCleared() {
		_spec.ClearField(role.FieldRoleCode, field.TypeString)
	}
	if ru.mutation.SysDeptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.SysDeptsTable,
			Columns: role.SysDeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedSysDeptsIDs(); len(nodes) > 0 && !ru.mutation.SysDeptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.SysDeptsTable,
			Columns: role.SysDeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.SysDeptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.SysDeptsTable,
			Columns: role.SysDeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.SysUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.SysUsersTable,
			Columns: role.SysUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedSysUsersIDs(); len(nodes) > 0 && !ru.mutation.SysUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.SysUsersTable,
			Columns: role.SysUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.SysUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.SysUsersTable,
			Columns: role.SysUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RoleUpdateOne is the builder for updating a single Role entity.
type RoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoleMutation
}

// SetRoleName sets the "role_name" field.
func (ruo *RoleUpdateOne) SetRoleName(s string) *RoleUpdateOne {
	ruo.mutation.SetRoleName(s)
	return ruo
}

// SetNillableRoleName sets the "role_name" field if the given value is not nil.
func (ruo *RoleUpdateOne) SetNillableRoleName(s *string) *RoleUpdateOne {
	if s != nil {
		ruo.SetRoleName(*s)
	}
	return ruo
}

// ClearRoleName clears the value of the "role_name" field.
func (ruo *RoleUpdateOne) ClearRoleName() *RoleUpdateOne {
	ruo.mutation.ClearRoleName()
	return ruo
}

// SetRoleCode sets the "role_code" field.
func (ruo *RoleUpdateOne) SetRoleCode(s string) *RoleUpdateOne {
	ruo.mutation.SetRoleCode(s)
	return ruo
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (ruo *RoleUpdateOne) SetNillableRoleCode(s *string) *RoleUpdateOne {
	if s != nil {
		ruo.SetRoleCode(*s)
	}
	return ruo
}

// ClearRoleCode clears the value of the "role_code" field.
func (ruo *RoleUpdateOne) ClearRoleCode() *RoleUpdateOne {
	ruo.mutation.ClearRoleCode()
	return ruo
}

// AddSysDeptIDs adds the "sysDepts" edge to the Dept entity by IDs.
func (ruo *RoleUpdateOne) AddSysDeptIDs(ids ...int64) *RoleUpdateOne {
	ruo.mutation.AddSysDeptIDs(ids...)
	return ruo
}

// AddSysDepts adds the "sysDepts" edges to the Dept entity.
func (ruo *RoleUpdateOne) AddSysDepts(d ...*Dept) *RoleUpdateOne {
	ids := make([]int64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return ruo.AddSysDeptIDs(ids...)
}

// AddSysUserIDs adds the "sysUsers" edge to the User entity by IDs.
func (ruo *RoleUpdateOne) AddSysUserIDs(ids ...int64) *RoleUpdateOne {
	ruo.mutation.AddSysUserIDs(ids...)
	return ruo
}

// AddSysUsers adds the "sysUsers" edges to the User entity.
func (ruo *RoleUpdateOne) AddSysUsers(u ...*User) *RoleUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ruo.AddSysUserIDs(ids...)
}

// Mutation returns the RoleMutation object of the builder.
func (ruo *RoleUpdateOne) Mutation() *RoleMutation {
	return ruo.mutation
}

// ClearSysDepts clears all "sysDepts" edges to the Dept entity.
func (ruo *RoleUpdateOne) ClearSysDepts() *RoleUpdateOne {
	ruo.mutation.ClearSysDepts()
	return ruo
}

// RemoveSysDeptIDs removes the "sysDepts" edge to Dept entities by IDs.
func (ruo *RoleUpdateOne) RemoveSysDeptIDs(ids ...int64) *RoleUpdateOne {
	ruo.mutation.RemoveSysDeptIDs(ids...)
	return ruo
}

// RemoveSysDepts removes "sysDepts" edges to Dept entities.
func (ruo *RoleUpdateOne) RemoveSysDepts(d ...*Dept) *RoleUpdateOne {
	ids := make([]int64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return ruo.RemoveSysDeptIDs(ids...)
}

// ClearSysUsers clears all "sysUsers" edges to the User entity.
func (ruo *RoleUpdateOne) ClearSysUsers() *RoleUpdateOne {
	ruo.mutation.ClearSysUsers()
	return ruo
}

// RemoveSysUserIDs removes the "sysUsers" edge to User entities by IDs.
func (ruo *RoleUpdateOne) RemoveSysUserIDs(ids ...int64) *RoleUpdateOne {
	ruo.mutation.RemoveSysUserIDs(ids...)
	return ruo
}

// RemoveSysUsers removes "sysUsers" edges to User entities.
func (ruo *RoleUpdateOne) RemoveSysUsers(u ...*User) *RoleUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return ruo.RemoveSysUserIDs(ids...)
}

// Where appends a list predicates to the RoleUpdate builder.
func (ruo *RoleUpdateOne) Where(ps ...predicate.Role) *RoleUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RoleUpdateOne) Select(field string, fields ...string) *RoleUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Role entity.
func (ruo *RoleUpdateOne) Save(ctx context.Context) (*Role, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoleUpdateOne) SaveX(ctx context.Context) *Role {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RoleUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoleUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RoleUpdateOne) sqlSave(ctx context.Context) (_node *Role, err error) {
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Role.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, role.FieldID)
		for _, f := range fields {
			if !role.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != role.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.RoleName(); ok {
		_spec.SetField(role.FieldRoleName, field.TypeString, value)
	}
	if ruo.mutation.RoleNameCleared() {
		_spec.ClearField(role.FieldRoleName, field.TypeString)
	}
	if value, ok := ruo.mutation.RoleCode(); ok {
		_spec.SetField(role.FieldRoleCode, field.TypeString, value)
	}
	if ruo.mutation.RoleCodeCleared() {
		_spec.ClearField(role.FieldRoleCode, field.TypeString)
	}
	if ruo.mutation.SysDeptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.SysDeptsTable,
			Columns: role.SysDeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedSysDeptsIDs(); len(nodes) > 0 && !ruo.mutation.SysDeptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.SysDeptsTable,
			Columns: role.SysDeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.SysDeptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.SysDeptsTable,
			Columns: role.SysDeptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dept.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.SysUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.SysUsersTable,
			Columns: role.SysUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedSysUsersIDs(); len(nodes) > 0 && !ruo.mutation.SysUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.SysUsersTable,
			Columns: role.SysUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.SysUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.SysUsersTable,
			Columns: role.SysUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Role{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
