// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-ent-demo/ent/sysrole"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 系统角色表
type SysRole struct {
	config `json:"-"`
	// ID of the ent.
	// 角色id
	ID int64 `json:"id,string"`
	// 角色名称
	RoleName string `json:"roleName"`
	// 角色编码
	RoleCode string `json:"roleCode"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysRoleQuery when eager-loading is set.
	Edges        SysRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysRoleEdges holds the relations/edges for other nodes in the graph.
type SysRoleEdges struct {
	// SysUsers holds the value of the sys_users edge.
	SysUsers []*SysUser `json:"sys_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SysUsersOrErr returns the SysUsers value or an error if the edge
// was not loaded in eager-loading.
func (e SysRoleEdges) SysUsersOrErr() ([]*SysUser, error) {
	if e.loadedTypes[0] {
		return e.SysUsers, nil
	}
	return nil, &NotLoadedError{edge: "sys_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysrole.FieldID:
			values[i] = new(sql.NullInt64)
		case sysrole.FieldRoleName, sysrole.FieldRoleCode:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysRole fields.
func (_m *SysRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysrole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sysrole.FieldRoleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_name", values[i])
			} else if value.Valid {
				_m.RoleName = value.String
			}
		case sysrole.FieldRoleCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_code", values[i])
			} else if value.Valid {
				_m.RoleCode = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysRole.
// This includes values selected through modifiers, order, etc.
func (_m *SysRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySysUsers queries the "sys_users" edge of the SysRole entity.
func (_m *SysRole) QuerySysUsers() *SysUserQuery {
	return NewSysRoleClient(_m.config).QuerySysUsers(_m)
}

// Update returns a builder for updating this SysRole.
// Note that you need to call SysRole.Unwrap() before calling this method if this SysRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysRole) Update() *SysRoleUpdateOne {
	return NewSysRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysRole) Unwrap() *SysRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysRole) String() string {
	var builder strings.Builder
	builder.WriteString("SysRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role_name=")
	builder.WriteString(_m.RoleName)
	builder.WriteString(", ")
	builder.WriteString("role_code=")
	builder.WriteString(_m.RoleCode)
	builder.WriteByte(')')
	return builder.String()
}

// SysRoles is a parsable slice of SysRole.
type SysRoles []*SysRole
