// Code generated by ent, DO NOT EDIT.

package entcore

import (
	"context"
	"errors"
	"fmt"
	"go-ent-demo/entcore/predicate"
	"go-ent-demo/entcore/sysmenu"
	"go-ent-demo/entcore/sysrole"
	"go-ent-demo/types"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysMenuUpdate is the builder for updating SysMenu entities.
type SysMenuUpdate struct {
	config
	hooks    []Hook
	mutation *SysMenuMutation
}

// Where appends a list predicates to the SysMenuUpdate builder.
func (_u *SysMenuUpdate) Where(ps ...predicate.SysMenu) *SysMenuUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *SysMenuUpdate) SetParentID(v types.ID) *SysMenuUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableParentID(v *types.ID) *SysMenuUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *SysMenuUpdate) ClearParentID() *SysMenuUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetSort sets the "sort" field.
func (_u *SysMenuUpdate) SetSort(v int) *SysMenuUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableSort(v *int) *SysMenuUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *SysMenuUpdate) AddSort(v int) *SysMenuUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SysMenuUpdate) SetStatus(v string) *SysMenuUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableStatus(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysMenuUpdate) SetCreatedBy(v string) *SysMenuUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableCreatedBy(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysMenuUpdate) ClearCreatedBy() *SysMenuUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SysMenuUpdate) SetCreatedAt(v types.CustomTime) *SysMenuUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *SysMenuUpdate) ClearCreatedAt() *SysMenuUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysMenuUpdate) SetUpdatedBy(v string) *SysMenuUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableUpdatedBy(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysMenuUpdate) ClearUpdatedBy() *SysMenuUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysMenuUpdate) SetUpdatedAt(v types.CustomTime) *SysMenuUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SysMenuUpdate) ClearUpdatedAt() *SysMenuUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SysMenuUpdate) SetDeletedBy(v string) *SysMenuUpdate {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableDeletedBy(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SysMenuUpdate) ClearDeletedBy() *SysMenuUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysMenuUpdate) SetDeletedAt(v time.Time) *SysMenuUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableDeletedAt(v *time.Time) *SysMenuUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysMenuUpdate) ClearDeletedAt() *SysMenuUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *SysMenuUpdate) SetRemark(v string) *SysMenuUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableRemark(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *SysMenuUpdate) ClearRemark() *SysMenuUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetDelFlag sets the "del_flag" field.
func (_u *SysMenuUpdate) SetDelFlag(v int8) *SysMenuUpdate {
	_u.mutation.ResetDelFlag()
	_u.mutation.SetDelFlag(v)
	return _u
}

// SetNillableDelFlag sets the "del_flag" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableDelFlag(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetDelFlag(*v)
	}
	return _u
}

// AddDelFlag adds value to the "del_flag" field.
func (_u *SysMenuUpdate) AddDelFlag(v int8) *SysMenuUpdate {
	_u.mutation.AddDelFlag(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SysMenuUpdate) SetName(v string) *SysMenuUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableName(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *SysMenuUpdate) SetPath(v string) *SysMenuUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillablePath(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *SysMenuUpdate) ClearPath() *SysMenuUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetType sets the "type" field.
func (_u *SysMenuUpdate) SetType(v int8) *SysMenuUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableType(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *SysMenuUpdate) AddType(v int8) *SysMenuUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetComponent sets the "component" field.
func (_u *SysMenuUpdate) SetComponent(v string) *SysMenuUpdate {
	_u.mutation.SetComponent(v)
	return _u
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableComponent(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetComponent(*v)
	}
	return _u
}

// SetPermission sets the "permission" field.
func (_u *SysMenuUpdate) SetPermission(v string) *SysMenuUpdate {
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillablePermission(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// ClearPermission clears the value of the "permission" field.
func (_u *SysMenuUpdate) ClearPermission() *SysMenuUpdate {
	_u.mutation.ClearPermission()
	return _u
}

// SetRedirect sets the "redirect" field.
func (_u *SysMenuUpdate) SetRedirect(v string) *SysMenuUpdate {
	_u.mutation.SetRedirect(v)
	return _u
}

// SetNillableRedirect sets the "redirect" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableRedirect(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetRedirect(*v)
	}
	return _u
}

// SetMetaTitle sets the "meta_title" field.
func (_u *SysMenuUpdate) SetMetaTitle(v string) *SysMenuUpdate {
	_u.mutation.SetMetaTitle(v)
	return _u
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaTitle(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaTitle(*v)
	}
	return _u
}

// SetMetaIcon sets the "meta_icon" field.
func (_u *SysMenuUpdate) SetMetaIcon(v string) *SysMenuUpdate {
	_u.mutation.SetMetaIcon(v)
	return _u
}

// SetNillableMetaIcon sets the "meta_icon" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaIcon(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaIcon(*v)
	}
	return _u
}

// SetMetaActiveIcon sets the "meta_active_icon" field.
func (_u *SysMenuUpdate) SetMetaActiveIcon(v string) *SysMenuUpdate {
	_u.mutation.SetMetaActiveIcon(v)
	return _u
}

// SetNillableMetaActiveIcon sets the "meta_active_icon" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaActiveIcon(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaActiveIcon(*v)
	}
	return _u
}

// SetMetaKeepAlive sets the "meta_keep_alive" field.
func (_u *SysMenuUpdate) SetMetaKeepAlive(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaKeepAlive()
	_u.mutation.SetMetaKeepAlive(v)
	return _u
}

// SetNillableMetaKeepAlive sets the "meta_keep_alive" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaKeepAlive(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaKeepAlive(*v)
	}
	return _u
}

// AddMetaKeepAlive adds value to the "meta_keep_alive" field.
func (_u *SysMenuUpdate) AddMetaKeepAlive(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaKeepAlive(v)
	return _u
}

// SetMetaHideInMenu sets the "meta_hide_in_menu" field.
func (_u *SysMenuUpdate) SetMetaHideInMenu(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaHideInMenu()
	_u.mutation.SetMetaHideInMenu(v)
	return _u
}

// SetNillableMetaHideInMenu sets the "meta_hide_in_menu" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaHideInMenu(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaHideInMenu(*v)
	}
	return _u
}

// AddMetaHideInMenu adds value to the "meta_hide_in_menu" field.
func (_u *SysMenuUpdate) AddMetaHideInMenu(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaHideInMenu(v)
	return _u
}

// SetMetaHideInTab sets the "meta_hide_in_tab" field.
func (_u *SysMenuUpdate) SetMetaHideInTab(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaHideInTab()
	_u.mutation.SetMetaHideInTab(v)
	return _u
}

// SetNillableMetaHideInTab sets the "meta_hide_in_tab" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaHideInTab(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaHideInTab(*v)
	}
	return _u
}

// AddMetaHideInTab adds value to the "meta_hide_in_tab" field.
func (_u *SysMenuUpdate) AddMetaHideInTab(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaHideInTab(v)
	return _u
}

// SetMetaHideInBreadcrumb sets the "meta_hide_in_breadcrumb" field.
func (_u *SysMenuUpdate) SetMetaHideInBreadcrumb(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaHideInBreadcrumb()
	_u.mutation.SetMetaHideInBreadcrumb(v)
	return _u
}

// SetNillableMetaHideInBreadcrumb sets the "meta_hide_in_breadcrumb" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaHideInBreadcrumb(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaHideInBreadcrumb(*v)
	}
	return _u
}

// AddMetaHideInBreadcrumb adds value to the "meta_hide_in_breadcrumb" field.
func (_u *SysMenuUpdate) AddMetaHideInBreadcrumb(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaHideInBreadcrumb(v)
	return _u
}

// SetMetaHideChildrenInMenu sets the "meta_hide_children_in_menu" field.
func (_u *SysMenuUpdate) SetMetaHideChildrenInMenu(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaHideChildrenInMenu()
	_u.mutation.SetMetaHideChildrenInMenu(v)
	return _u
}

// SetNillableMetaHideChildrenInMenu sets the "meta_hide_children_in_menu" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaHideChildrenInMenu(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaHideChildrenInMenu(*v)
	}
	return _u
}

// AddMetaHideChildrenInMenu adds value to the "meta_hide_children_in_menu" field.
func (_u *SysMenuUpdate) AddMetaHideChildrenInMenu(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaHideChildrenInMenu(v)
	return _u
}

// SetMetaAuthority sets the "meta_authority" field.
func (_u *SysMenuUpdate) SetMetaAuthority(v string) *SysMenuUpdate {
	_u.mutation.SetMetaAuthority(v)
	return _u
}

// SetNillableMetaAuthority sets the "meta_authority" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaAuthority(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaAuthority(*v)
	}
	return _u
}

// SetMetaBadge sets the "meta_badge" field.
func (_u *SysMenuUpdate) SetMetaBadge(v string) *SysMenuUpdate {
	_u.mutation.SetMetaBadge(v)
	return _u
}

// SetNillableMetaBadge sets the "meta_badge" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaBadge(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaBadge(*v)
	}
	return _u
}

// SetMetaBadgeType sets the "meta_badge_type" field.
func (_u *SysMenuUpdate) SetMetaBadgeType(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaBadgeType()
	_u.mutation.SetMetaBadgeType(v)
	return _u
}

// SetNillableMetaBadgeType sets the "meta_badge_type" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaBadgeType(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaBadgeType(*v)
	}
	return _u
}

// AddMetaBadgeType adds value to the "meta_badge_type" field.
func (_u *SysMenuUpdate) AddMetaBadgeType(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaBadgeType(v)
	return _u
}

// SetMetaBadgeVariants sets the "meta_badge_variants" field.
func (_u *SysMenuUpdate) SetMetaBadgeVariants(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaBadgeVariants()
	_u.mutation.SetMetaBadgeVariants(v)
	return _u
}

// SetNillableMetaBadgeVariants sets the "meta_badge_variants" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaBadgeVariants(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaBadgeVariants(*v)
	}
	return _u
}

// AddMetaBadgeVariants adds value to the "meta_badge_variants" field.
func (_u *SysMenuUpdate) AddMetaBadgeVariants(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaBadgeVariants(v)
	return _u
}

// SetMetaFullPathKey sets the "meta_full_path_key" field.
func (_u *SysMenuUpdate) SetMetaFullPathKey(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaFullPathKey()
	_u.mutation.SetMetaFullPathKey(v)
	return _u
}

// SetNillableMetaFullPathKey sets the "meta_full_path_key" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaFullPathKey(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaFullPathKey(*v)
	}
	return _u
}

// AddMetaFullPathKey adds value to the "meta_full_path_key" field.
func (_u *SysMenuUpdate) AddMetaFullPathKey(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaFullPathKey(v)
	return _u
}

// SetMetaActivePath sets the "meta_active_path" field.
func (_u *SysMenuUpdate) SetMetaActivePath(v string) *SysMenuUpdate {
	_u.mutation.SetMetaActivePath(v)
	return _u
}

// SetNillableMetaActivePath sets the "meta_active_path" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaActivePath(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaActivePath(*v)
	}
	return _u
}

// SetMetaAffixTab sets the "meta_affix_tab" field.
func (_u *SysMenuUpdate) SetMetaAffixTab(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaAffixTab()
	_u.mutation.SetMetaAffixTab(v)
	return _u
}

// SetNillableMetaAffixTab sets the "meta_affix_tab" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaAffixTab(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaAffixTab(*v)
	}
	return _u
}

// AddMetaAffixTab adds value to the "meta_affix_tab" field.
func (_u *SysMenuUpdate) AddMetaAffixTab(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaAffixTab(v)
	return _u
}

// SetMetaAffixTabOrder sets the "meta_affix_tab_order" field.
func (_u *SysMenuUpdate) SetMetaAffixTabOrder(v int) *SysMenuUpdate {
	_u.mutation.ResetMetaAffixTabOrder()
	_u.mutation.SetMetaAffixTabOrder(v)
	return _u
}

// SetNillableMetaAffixTabOrder sets the "meta_affix_tab_order" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaAffixTabOrder(v *int) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaAffixTabOrder(*v)
	}
	return _u
}

// AddMetaAffixTabOrder adds value to the "meta_affix_tab_order" field.
func (_u *SysMenuUpdate) AddMetaAffixTabOrder(v int) *SysMenuUpdate {
	_u.mutation.AddMetaAffixTabOrder(v)
	return _u
}

// SetMetaIframeSrc sets the "meta_iframe_src" field.
func (_u *SysMenuUpdate) SetMetaIframeSrc(v string) *SysMenuUpdate {
	_u.mutation.SetMetaIframeSrc(v)
	return _u
}

// SetNillableMetaIframeSrc sets the "meta_iframe_src" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaIframeSrc(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaIframeSrc(*v)
	}
	return _u
}

// SetMetaIgnoreAccess sets the "meta_ignore_access" field.
func (_u *SysMenuUpdate) SetMetaIgnoreAccess(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaIgnoreAccess()
	_u.mutation.SetMetaIgnoreAccess(v)
	return _u
}

// SetNillableMetaIgnoreAccess sets the "meta_ignore_access" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaIgnoreAccess(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaIgnoreAccess(*v)
	}
	return _u
}

// AddMetaIgnoreAccess adds value to the "meta_ignore_access" field.
func (_u *SysMenuUpdate) AddMetaIgnoreAccess(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaIgnoreAccess(v)
	return _u
}

// SetMetaLink sets the "meta_link" field.
func (_u *SysMenuUpdate) SetMetaLink(v string) *SysMenuUpdate {
	_u.mutation.SetMetaLink(v)
	return _u
}

// SetNillableMetaLink sets the "meta_link" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaLink(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaLink(*v)
	}
	return _u
}

// SetMetaMaxNumOfOpenTab sets the "meta_max_num_of_open_tab" field.
func (_u *SysMenuUpdate) SetMetaMaxNumOfOpenTab(v int) *SysMenuUpdate {
	_u.mutation.ResetMetaMaxNumOfOpenTab()
	_u.mutation.SetMetaMaxNumOfOpenTab(v)
	return _u
}

// SetNillableMetaMaxNumOfOpenTab sets the "meta_max_num_of_open_tab" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaMaxNumOfOpenTab(v *int) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaMaxNumOfOpenTab(*v)
	}
	return _u
}

// AddMetaMaxNumOfOpenTab adds value to the "meta_max_num_of_open_tab" field.
func (_u *SysMenuUpdate) AddMetaMaxNumOfOpenTab(v int) *SysMenuUpdate {
	_u.mutation.AddMetaMaxNumOfOpenTab(v)
	return _u
}

// SetMetaMenuVisibleWithForbidden sets the "meta_menu_visible_with_forbidden" field.
func (_u *SysMenuUpdate) SetMetaMenuVisibleWithForbidden(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaMenuVisibleWithForbidden()
	_u.mutation.SetMetaMenuVisibleWithForbidden(v)
	return _u
}

// SetNillableMetaMenuVisibleWithForbidden sets the "meta_menu_visible_with_forbidden" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaMenuVisibleWithForbidden(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaMenuVisibleWithForbidden(*v)
	}
	return _u
}

// AddMetaMenuVisibleWithForbidden adds value to the "meta_menu_visible_with_forbidden" field.
func (_u *SysMenuUpdate) AddMetaMenuVisibleWithForbidden(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaMenuVisibleWithForbidden(v)
	return _u
}

// SetMetaOpenInNewWindow sets the "meta_open_in_new_window" field.
func (_u *SysMenuUpdate) SetMetaOpenInNewWindow(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaOpenInNewWindow()
	_u.mutation.SetMetaOpenInNewWindow(v)
	return _u
}

// SetNillableMetaOpenInNewWindow sets the "meta_open_in_new_window" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaOpenInNewWindow(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaOpenInNewWindow(*v)
	}
	return _u
}

// AddMetaOpenInNewWindow adds value to the "meta_open_in_new_window" field.
func (_u *SysMenuUpdate) AddMetaOpenInNewWindow(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaOpenInNewWindow(v)
	return _u
}

// SetMetaOrder sets the "meta_order" field.
func (_u *SysMenuUpdate) SetMetaOrder(v int) *SysMenuUpdate {
	_u.mutation.ResetMetaOrder()
	_u.mutation.SetMetaOrder(v)
	return _u
}

// SetNillableMetaOrder sets the "meta_order" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaOrder(v *int) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaOrder(*v)
	}
	return _u
}

// AddMetaOrder adds value to the "meta_order" field.
func (_u *SysMenuUpdate) AddMetaOrder(v int) *SysMenuUpdate {
	_u.mutation.AddMetaOrder(v)
	return _u
}

// SetMetaQuery sets the "meta_query" field.
func (_u *SysMenuUpdate) SetMetaQuery(v string) *SysMenuUpdate {
	_u.mutation.SetMetaQuery(v)
	return _u
}

// SetNillableMetaQuery sets the "meta_query" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaQuery(v *string) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaQuery(*v)
	}
	return _u
}

// SetMetaNoBasicLayout sets the "meta_no_basic_layout" field.
func (_u *SysMenuUpdate) SetMetaNoBasicLayout(v int8) *SysMenuUpdate {
	_u.mutation.ResetMetaNoBasicLayout()
	_u.mutation.SetMetaNoBasicLayout(v)
	return _u
}

// SetNillableMetaNoBasicLayout sets the "meta_no_basic_layout" field if the given value is not nil.
func (_u *SysMenuUpdate) SetNillableMetaNoBasicLayout(v *int8) *SysMenuUpdate {
	if v != nil {
		_u.SetMetaNoBasicLayout(*v)
	}
	return _u
}

// AddMetaNoBasicLayout adds value to the "meta_no_basic_layout" field.
func (_u *SysMenuUpdate) AddMetaNoBasicLayout(v int8) *SysMenuUpdate {
	_u.mutation.AddMetaNoBasicLayout(v)
	return _u
}

// AddSysRoleIDs adds the "sysRoles" edge to the SysRole entity by IDs.
func (_u *SysMenuUpdate) AddSysRoleIDs(ids ...types.ID) *SysMenuUpdate {
	_u.mutation.AddSysRoleIDs(ids...)
	return _u
}

// AddSysRoles adds the "sysRoles" edges to the SysRole entity.
func (_u *SysMenuUpdate) AddSysRoles(v ...*SysRole) *SysMenuUpdate {
	ids := make([]types.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSysRoleIDs(ids...)
}

// SetParent sets the "parent" edge to the SysMenu entity.
func (_u *SysMenuUpdate) SetParent(v *SysMenu) *SysMenuUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the SysMenu entity by IDs.
func (_u *SysMenuUpdate) AddChildIDs(ids ...types.ID) *SysMenuUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the SysMenu entity.
func (_u *SysMenuUpdate) AddChildren(v ...*SysMenu) *SysMenuUpdate {
	ids := make([]types.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the SysMenuMutation object of the builder.
func (_u *SysMenuUpdate) Mutation() *SysMenuMutation {
	return _u.mutation
}

// ClearSysRoles clears all "sysRoles" edges to the SysRole entity.
func (_u *SysMenuUpdate) ClearSysRoles() *SysMenuUpdate {
	_u.mutation.ClearSysRoles()
	return _u
}

// RemoveSysRoleIDs removes the "sysRoles" edge to SysRole entities by IDs.
func (_u *SysMenuUpdate) RemoveSysRoleIDs(ids ...types.ID) *SysMenuUpdate {
	_u.mutation.RemoveSysRoleIDs(ids...)
	return _u
}

// RemoveSysRoles removes "sysRoles" edges to SysRole entities.
func (_u *SysMenuUpdate) RemoveSysRoles(v ...*SysRole) *SysMenuUpdate {
	ids := make([]types.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSysRoleIDs(ids...)
}

// ClearParent clears the "parent" edge to the SysMenu entity.
func (_u *SysMenuUpdate) ClearParent() *SysMenuUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the SysMenu entity.
func (_u *SysMenuUpdate) ClearChildren() *SysMenuUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to SysMenu entities by IDs.
func (_u *SysMenuUpdate) RemoveChildIDs(ids ...types.ID) *SysMenuUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to SysMenu entities.
func (_u *SysMenuUpdate) RemoveChildren(v ...*SysMenu) *SysMenuUpdate {
	ids := make([]types.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysMenuUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysMenuUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysMenuUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysMenuUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SysMenuUpdate) defaults() error {
	if _, ok := _u.mutation.CreatedAt(); !ok && !_u.mutation.CreatedAtCleared() {
		if sysmenu.UpdateDefaultCreatedAt == nil {
			return fmt.Errorf("entcore: uninitialized sysmenu.UpdateDefaultCreatedAt (forgotten import entcore/runtime?)")
		}
		v := sysmenu.UpdateDefaultCreatedAt()
		_u.mutation.SetCreatedAt(v)
	}
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		if sysmenu.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("entcore: uninitialized sysmenu.UpdateDefaultUpdatedAt (forgotten import entcore/runtime?)")
		}
		v := sysmenu.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *SysMenuUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysmenu.Table, sysmenu.Columns, sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(sysmenu.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(sysmenu.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sysmenu.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysmenu.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysmenu.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sysmenu.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(sysmenu.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysmenu.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysmenu.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysmenu.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(sysmenu.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(sysmenu.FieldDeletedBy, field.TypeString, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(sysmenu.FieldDeletedBy, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysmenu.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysmenu.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(sysmenu.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(sysmenu.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.DelFlag(); ok {
		_spec.SetField(sysmenu.FieldDelFlag, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDelFlag(); ok {
		_spec.AddField(sysmenu.FieldDelFlag, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sysmenu.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(sysmenu.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(sysmenu.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(sysmenu.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(sysmenu.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Component(); ok {
		_spec.SetField(sysmenu.FieldComponent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(sysmenu.FieldPermission, field.TypeString, value)
	}
	if _u.mutation.PermissionCleared() {
		_spec.ClearField(sysmenu.FieldPermission, field.TypeString)
	}
	if value, ok := _u.mutation.Redirect(); ok {
		_spec.SetField(sysmenu.FieldRedirect, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaTitle(); ok {
		_spec.SetField(sysmenu.FieldMetaTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaIcon(); ok {
		_spec.SetField(sysmenu.FieldMetaIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaActiveIcon(); ok {
		_spec.SetField(sysmenu.FieldMetaActiveIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaKeepAlive(); ok {
		_spec.SetField(sysmenu.FieldMetaKeepAlive, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaKeepAlive(); ok {
		_spec.AddField(sysmenu.FieldMetaKeepAlive, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaHideInMenu(); ok {
		_spec.SetField(sysmenu.FieldMetaHideInMenu, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaHideInMenu(); ok {
		_spec.AddField(sysmenu.FieldMetaHideInMenu, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaHideInTab(); ok {
		_spec.SetField(sysmenu.FieldMetaHideInTab, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaHideInTab(); ok {
		_spec.AddField(sysmenu.FieldMetaHideInTab, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaHideInBreadcrumb(); ok {
		_spec.SetField(sysmenu.FieldMetaHideInBreadcrumb, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaHideInBreadcrumb(); ok {
		_spec.AddField(sysmenu.FieldMetaHideInBreadcrumb, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaHideChildrenInMenu(); ok {
		_spec.SetField(sysmenu.FieldMetaHideChildrenInMenu, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaHideChildrenInMenu(); ok {
		_spec.AddField(sysmenu.FieldMetaHideChildrenInMenu, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaAuthority(); ok {
		_spec.SetField(sysmenu.FieldMetaAuthority, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaBadge(); ok {
		_spec.SetField(sysmenu.FieldMetaBadge, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaBadgeType(); ok {
		_spec.SetField(sysmenu.FieldMetaBadgeType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaBadgeType(); ok {
		_spec.AddField(sysmenu.FieldMetaBadgeType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaBadgeVariants(); ok {
		_spec.SetField(sysmenu.FieldMetaBadgeVariants, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaBadgeVariants(); ok {
		_spec.AddField(sysmenu.FieldMetaBadgeVariants, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaFullPathKey(); ok {
		_spec.SetField(sysmenu.FieldMetaFullPathKey, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaFullPathKey(); ok {
		_spec.AddField(sysmenu.FieldMetaFullPathKey, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaActivePath(); ok {
		_spec.SetField(sysmenu.FieldMetaActivePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaAffixTab(); ok {
		_spec.SetField(sysmenu.FieldMetaAffixTab, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaAffixTab(); ok {
		_spec.AddField(sysmenu.FieldMetaAffixTab, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaAffixTabOrder(); ok {
		_spec.SetField(sysmenu.FieldMetaAffixTabOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetaAffixTabOrder(); ok {
		_spec.AddField(sysmenu.FieldMetaAffixTabOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetaIframeSrc(); ok {
		_spec.SetField(sysmenu.FieldMetaIframeSrc, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaIgnoreAccess(); ok {
		_spec.SetField(sysmenu.FieldMetaIgnoreAccess, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaIgnoreAccess(); ok {
		_spec.AddField(sysmenu.FieldMetaIgnoreAccess, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaLink(); ok {
		_spec.SetField(sysmenu.FieldMetaLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaMaxNumOfOpenTab(); ok {
		_spec.SetField(sysmenu.FieldMetaMaxNumOfOpenTab, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetaMaxNumOfOpenTab(); ok {
		_spec.AddField(sysmenu.FieldMetaMaxNumOfOpenTab, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetaMenuVisibleWithForbidden(); ok {
		_spec.SetField(sysmenu.FieldMetaMenuVisibleWithForbidden, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaMenuVisibleWithForbidden(); ok {
		_spec.AddField(sysmenu.FieldMetaMenuVisibleWithForbidden, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaOpenInNewWindow(); ok {
		_spec.SetField(sysmenu.FieldMetaOpenInNewWindow, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaOpenInNewWindow(); ok {
		_spec.AddField(sysmenu.FieldMetaOpenInNewWindow, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaOrder(); ok {
		_spec.SetField(sysmenu.FieldMetaOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetaOrder(); ok {
		_spec.AddField(sysmenu.FieldMetaOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetaQuery(); ok {
		_spec.SetField(sysmenu.FieldMetaQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaNoBasicLayout(); ok {
		_spec.SetField(sysmenu.FieldMetaNoBasicLayout, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaNoBasicLayout(); ok {
		_spec.AddField(sysmenu.FieldMetaNoBasicLayout, field.TypeInt8, value)
	}
	if _u.mutation.SysRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   sysmenu.SysRolesTable,
			Columns: sysmenu.SysRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSysRolesIDs(); len(nodes) > 0 && !_u.mutation.SysRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   sysmenu.SysRolesTable,
			Columns: sysmenu.SysRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SysRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   sysmenu.SysRolesTable,
			Columns: sysmenu.SysRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysmenu.ParentTable,
			Columns: []string{sysmenu.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysmenu.ParentTable,
			Columns: []string{sysmenu.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysmenu.ChildrenTable,
			Columns: []string{sysmenu.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysmenu.ChildrenTable,
			Columns: []string{sysmenu.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysmenu.ChildrenTable,
			Columns: []string{sysmenu.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysMenuUpdateOne is the builder for updating a single SysMenu entity.
type SysMenuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysMenuMutation
}

// SetParentID sets the "parent_id" field.
func (_u *SysMenuUpdateOne) SetParentID(v types.ID) *SysMenuUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableParentID(v *types.ID) *SysMenuUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *SysMenuUpdateOne) ClearParentID() *SysMenuUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetSort sets the "sort" field.
func (_u *SysMenuUpdateOne) SetSort(v int) *SysMenuUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableSort(v *int) *SysMenuUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *SysMenuUpdateOne) AddSort(v int) *SysMenuUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SysMenuUpdateOne) SetStatus(v string) *SysMenuUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableStatus(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysMenuUpdateOne) SetCreatedBy(v string) *SysMenuUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableCreatedBy(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysMenuUpdateOne) ClearCreatedBy() *SysMenuUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SysMenuUpdateOne) SetCreatedAt(v types.CustomTime) *SysMenuUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *SysMenuUpdateOne) ClearCreatedAt() *SysMenuUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysMenuUpdateOne) SetUpdatedBy(v string) *SysMenuUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableUpdatedBy(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysMenuUpdateOne) ClearUpdatedBy() *SysMenuUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysMenuUpdateOne) SetUpdatedAt(v types.CustomTime) *SysMenuUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SysMenuUpdateOne) ClearUpdatedAt() *SysMenuUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SysMenuUpdateOne) SetDeletedBy(v string) *SysMenuUpdateOne {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableDeletedBy(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SysMenuUpdateOne) ClearDeletedBy() *SysMenuUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysMenuUpdateOne) SetDeletedAt(v time.Time) *SysMenuUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableDeletedAt(v *time.Time) *SysMenuUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysMenuUpdateOne) ClearDeletedAt() *SysMenuUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *SysMenuUpdateOne) SetRemark(v string) *SysMenuUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableRemark(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *SysMenuUpdateOne) ClearRemark() *SysMenuUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetDelFlag sets the "del_flag" field.
func (_u *SysMenuUpdateOne) SetDelFlag(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetDelFlag()
	_u.mutation.SetDelFlag(v)
	return _u
}

// SetNillableDelFlag sets the "del_flag" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableDelFlag(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetDelFlag(*v)
	}
	return _u
}

// AddDelFlag adds value to the "del_flag" field.
func (_u *SysMenuUpdateOne) AddDelFlag(v int8) *SysMenuUpdateOne {
	_u.mutation.AddDelFlag(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SysMenuUpdateOne) SetName(v string) *SysMenuUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableName(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *SysMenuUpdateOne) SetPath(v string) *SysMenuUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillablePath(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *SysMenuUpdateOne) ClearPath() *SysMenuUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetType sets the "type" field.
func (_u *SysMenuUpdateOne) SetType(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableType(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *SysMenuUpdateOne) AddType(v int8) *SysMenuUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetComponent sets the "component" field.
func (_u *SysMenuUpdateOne) SetComponent(v string) *SysMenuUpdateOne {
	_u.mutation.SetComponent(v)
	return _u
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableComponent(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetComponent(*v)
	}
	return _u
}

// SetPermission sets the "permission" field.
func (_u *SysMenuUpdateOne) SetPermission(v string) *SysMenuUpdateOne {
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillablePermission(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// ClearPermission clears the value of the "permission" field.
func (_u *SysMenuUpdateOne) ClearPermission() *SysMenuUpdateOne {
	_u.mutation.ClearPermission()
	return _u
}

// SetRedirect sets the "redirect" field.
func (_u *SysMenuUpdateOne) SetRedirect(v string) *SysMenuUpdateOne {
	_u.mutation.SetRedirect(v)
	return _u
}

// SetNillableRedirect sets the "redirect" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableRedirect(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetRedirect(*v)
	}
	return _u
}

// SetMetaTitle sets the "meta_title" field.
func (_u *SysMenuUpdateOne) SetMetaTitle(v string) *SysMenuUpdateOne {
	_u.mutation.SetMetaTitle(v)
	return _u
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaTitle(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaTitle(*v)
	}
	return _u
}

// SetMetaIcon sets the "meta_icon" field.
func (_u *SysMenuUpdateOne) SetMetaIcon(v string) *SysMenuUpdateOne {
	_u.mutation.SetMetaIcon(v)
	return _u
}

// SetNillableMetaIcon sets the "meta_icon" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaIcon(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaIcon(*v)
	}
	return _u
}

// SetMetaActiveIcon sets the "meta_active_icon" field.
func (_u *SysMenuUpdateOne) SetMetaActiveIcon(v string) *SysMenuUpdateOne {
	_u.mutation.SetMetaActiveIcon(v)
	return _u
}

// SetNillableMetaActiveIcon sets the "meta_active_icon" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaActiveIcon(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaActiveIcon(*v)
	}
	return _u
}

// SetMetaKeepAlive sets the "meta_keep_alive" field.
func (_u *SysMenuUpdateOne) SetMetaKeepAlive(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaKeepAlive()
	_u.mutation.SetMetaKeepAlive(v)
	return _u
}

// SetNillableMetaKeepAlive sets the "meta_keep_alive" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaKeepAlive(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaKeepAlive(*v)
	}
	return _u
}

// AddMetaKeepAlive adds value to the "meta_keep_alive" field.
func (_u *SysMenuUpdateOne) AddMetaKeepAlive(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaKeepAlive(v)
	return _u
}

// SetMetaHideInMenu sets the "meta_hide_in_menu" field.
func (_u *SysMenuUpdateOne) SetMetaHideInMenu(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaHideInMenu()
	_u.mutation.SetMetaHideInMenu(v)
	return _u
}

// SetNillableMetaHideInMenu sets the "meta_hide_in_menu" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaHideInMenu(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaHideInMenu(*v)
	}
	return _u
}

// AddMetaHideInMenu adds value to the "meta_hide_in_menu" field.
func (_u *SysMenuUpdateOne) AddMetaHideInMenu(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaHideInMenu(v)
	return _u
}

// SetMetaHideInTab sets the "meta_hide_in_tab" field.
func (_u *SysMenuUpdateOne) SetMetaHideInTab(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaHideInTab()
	_u.mutation.SetMetaHideInTab(v)
	return _u
}

// SetNillableMetaHideInTab sets the "meta_hide_in_tab" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaHideInTab(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaHideInTab(*v)
	}
	return _u
}

// AddMetaHideInTab adds value to the "meta_hide_in_tab" field.
func (_u *SysMenuUpdateOne) AddMetaHideInTab(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaHideInTab(v)
	return _u
}

// SetMetaHideInBreadcrumb sets the "meta_hide_in_breadcrumb" field.
func (_u *SysMenuUpdateOne) SetMetaHideInBreadcrumb(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaHideInBreadcrumb()
	_u.mutation.SetMetaHideInBreadcrumb(v)
	return _u
}

// SetNillableMetaHideInBreadcrumb sets the "meta_hide_in_breadcrumb" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaHideInBreadcrumb(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaHideInBreadcrumb(*v)
	}
	return _u
}

// AddMetaHideInBreadcrumb adds value to the "meta_hide_in_breadcrumb" field.
func (_u *SysMenuUpdateOne) AddMetaHideInBreadcrumb(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaHideInBreadcrumb(v)
	return _u
}

// SetMetaHideChildrenInMenu sets the "meta_hide_children_in_menu" field.
func (_u *SysMenuUpdateOne) SetMetaHideChildrenInMenu(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaHideChildrenInMenu()
	_u.mutation.SetMetaHideChildrenInMenu(v)
	return _u
}

// SetNillableMetaHideChildrenInMenu sets the "meta_hide_children_in_menu" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaHideChildrenInMenu(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaHideChildrenInMenu(*v)
	}
	return _u
}

// AddMetaHideChildrenInMenu adds value to the "meta_hide_children_in_menu" field.
func (_u *SysMenuUpdateOne) AddMetaHideChildrenInMenu(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaHideChildrenInMenu(v)
	return _u
}

// SetMetaAuthority sets the "meta_authority" field.
func (_u *SysMenuUpdateOne) SetMetaAuthority(v string) *SysMenuUpdateOne {
	_u.mutation.SetMetaAuthority(v)
	return _u
}

// SetNillableMetaAuthority sets the "meta_authority" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaAuthority(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaAuthority(*v)
	}
	return _u
}

// SetMetaBadge sets the "meta_badge" field.
func (_u *SysMenuUpdateOne) SetMetaBadge(v string) *SysMenuUpdateOne {
	_u.mutation.SetMetaBadge(v)
	return _u
}

// SetNillableMetaBadge sets the "meta_badge" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaBadge(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaBadge(*v)
	}
	return _u
}

// SetMetaBadgeType sets the "meta_badge_type" field.
func (_u *SysMenuUpdateOne) SetMetaBadgeType(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaBadgeType()
	_u.mutation.SetMetaBadgeType(v)
	return _u
}

// SetNillableMetaBadgeType sets the "meta_badge_type" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaBadgeType(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaBadgeType(*v)
	}
	return _u
}

// AddMetaBadgeType adds value to the "meta_badge_type" field.
func (_u *SysMenuUpdateOne) AddMetaBadgeType(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaBadgeType(v)
	return _u
}

// SetMetaBadgeVariants sets the "meta_badge_variants" field.
func (_u *SysMenuUpdateOne) SetMetaBadgeVariants(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaBadgeVariants()
	_u.mutation.SetMetaBadgeVariants(v)
	return _u
}

// SetNillableMetaBadgeVariants sets the "meta_badge_variants" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaBadgeVariants(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaBadgeVariants(*v)
	}
	return _u
}

// AddMetaBadgeVariants adds value to the "meta_badge_variants" field.
func (_u *SysMenuUpdateOne) AddMetaBadgeVariants(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaBadgeVariants(v)
	return _u
}

// SetMetaFullPathKey sets the "meta_full_path_key" field.
func (_u *SysMenuUpdateOne) SetMetaFullPathKey(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaFullPathKey()
	_u.mutation.SetMetaFullPathKey(v)
	return _u
}

// SetNillableMetaFullPathKey sets the "meta_full_path_key" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaFullPathKey(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaFullPathKey(*v)
	}
	return _u
}

// AddMetaFullPathKey adds value to the "meta_full_path_key" field.
func (_u *SysMenuUpdateOne) AddMetaFullPathKey(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaFullPathKey(v)
	return _u
}

// SetMetaActivePath sets the "meta_active_path" field.
func (_u *SysMenuUpdateOne) SetMetaActivePath(v string) *SysMenuUpdateOne {
	_u.mutation.SetMetaActivePath(v)
	return _u
}

// SetNillableMetaActivePath sets the "meta_active_path" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaActivePath(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaActivePath(*v)
	}
	return _u
}

// SetMetaAffixTab sets the "meta_affix_tab" field.
func (_u *SysMenuUpdateOne) SetMetaAffixTab(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaAffixTab()
	_u.mutation.SetMetaAffixTab(v)
	return _u
}

// SetNillableMetaAffixTab sets the "meta_affix_tab" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaAffixTab(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaAffixTab(*v)
	}
	return _u
}

// AddMetaAffixTab adds value to the "meta_affix_tab" field.
func (_u *SysMenuUpdateOne) AddMetaAffixTab(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaAffixTab(v)
	return _u
}

// SetMetaAffixTabOrder sets the "meta_affix_tab_order" field.
func (_u *SysMenuUpdateOne) SetMetaAffixTabOrder(v int) *SysMenuUpdateOne {
	_u.mutation.ResetMetaAffixTabOrder()
	_u.mutation.SetMetaAffixTabOrder(v)
	return _u
}

// SetNillableMetaAffixTabOrder sets the "meta_affix_tab_order" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaAffixTabOrder(v *int) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaAffixTabOrder(*v)
	}
	return _u
}

// AddMetaAffixTabOrder adds value to the "meta_affix_tab_order" field.
func (_u *SysMenuUpdateOne) AddMetaAffixTabOrder(v int) *SysMenuUpdateOne {
	_u.mutation.AddMetaAffixTabOrder(v)
	return _u
}

// SetMetaIframeSrc sets the "meta_iframe_src" field.
func (_u *SysMenuUpdateOne) SetMetaIframeSrc(v string) *SysMenuUpdateOne {
	_u.mutation.SetMetaIframeSrc(v)
	return _u
}

// SetNillableMetaIframeSrc sets the "meta_iframe_src" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaIframeSrc(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaIframeSrc(*v)
	}
	return _u
}

// SetMetaIgnoreAccess sets the "meta_ignore_access" field.
func (_u *SysMenuUpdateOne) SetMetaIgnoreAccess(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaIgnoreAccess()
	_u.mutation.SetMetaIgnoreAccess(v)
	return _u
}

// SetNillableMetaIgnoreAccess sets the "meta_ignore_access" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaIgnoreAccess(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaIgnoreAccess(*v)
	}
	return _u
}

// AddMetaIgnoreAccess adds value to the "meta_ignore_access" field.
func (_u *SysMenuUpdateOne) AddMetaIgnoreAccess(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaIgnoreAccess(v)
	return _u
}

// SetMetaLink sets the "meta_link" field.
func (_u *SysMenuUpdateOne) SetMetaLink(v string) *SysMenuUpdateOne {
	_u.mutation.SetMetaLink(v)
	return _u
}

// SetNillableMetaLink sets the "meta_link" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaLink(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaLink(*v)
	}
	return _u
}

// SetMetaMaxNumOfOpenTab sets the "meta_max_num_of_open_tab" field.
func (_u *SysMenuUpdateOne) SetMetaMaxNumOfOpenTab(v int) *SysMenuUpdateOne {
	_u.mutation.ResetMetaMaxNumOfOpenTab()
	_u.mutation.SetMetaMaxNumOfOpenTab(v)
	return _u
}

// SetNillableMetaMaxNumOfOpenTab sets the "meta_max_num_of_open_tab" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaMaxNumOfOpenTab(v *int) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaMaxNumOfOpenTab(*v)
	}
	return _u
}

// AddMetaMaxNumOfOpenTab adds value to the "meta_max_num_of_open_tab" field.
func (_u *SysMenuUpdateOne) AddMetaMaxNumOfOpenTab(v int) *SysMenuUpdateOne {
	_u.mutation.AddMetaMaxNumOfOpenTab(v)
	return _u
}

// SetMetaMenuVisibleWithForbidden sets the "meta_menu_visible_with_forbidden" field.
func (_u *SysMenuUpdateOne) SetMetaMenuVisibleWithForbidden(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaMenuVisibleWithForbidden()
	_u.mutation.SetMetaMenuVisibleWithForbidden(v)
	return _u
}

// SetNillableMetaMenuVisibleWithForbidden sets the "meta_menu_visible_with_forbidden" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaMenuVisibleWithForbidden(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaMenuVisibleWithForbidden(*v)
	}
	return _u
}

// AddMetaMenuVisibleWithForbidden adds value to the "meta_menu_visible_with_forbidden" field.
func (_u *SysMenuUpdateOne) AddMetaMenuVisibleWithForbidden(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaMenuVisibleWithForbidden(v)
	return _u
}

// SetMetaOpenInNewWindow sets the "meta_open_in_new_window" field.
func (_u *SysMenuUpdateOne) SetMetaOpenInNewWindow(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaOpenInNewWindow()
	_u.mutation.SetMetaOpenInNewWindow(v)
	return _u
}

// SetNillableMetaOpenInNewWindow sets the "meta_open_in_new_window" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaOpenInNewWindow(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaOpenInNewWindow(*v)
	}
	return _u
}

// AddMetaOpenInNewWindow adds value to the "meta_open_in_new_window" field.
func (_u *SysMenuUpdateOne) AddMetaOpenInNewWindow(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaOpenInNewWindow(v)
	return _u
}

// SetMetaOrder sets the "meta_order" field.
func (_u *SysMenuUpdateOne) SetMetaOrder(v int) *SysMenuUpdateOne {
	_u.mutation.ResetMetaOrder()
	_u.mutation.SetMetaOrder(v)
	return _u
}

// SetNillableMetaOrder sets the "meta_order" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaOrder(v *int) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaOrder(*v)
	}
	return _u
}

// AddMetaOrder adds value to the "meta_order" field.
func (_u *SysMenuUpdateOne) AddMetaOrder(v int) *SysMenuUpdateOne {
	_u.mutation.AddMetaOrder(v)
	return _u
}

// SetMetaQuery sets the "meta_query" field.
func (_u *SysMenuUpdateOne) SetMetaQuery(v string) *SysMenuUpdateOne {
	_u.mutation.SetMetaQuery(v)
	return _u
}

// SetNillableMetaQuery sets the "meta_query" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaQuery(v *string) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaQuery(*v)
	}
	return _u
}

// SetMetaNoBasicLayout sets the "meta_no_basic_layout" field.
func (_u *SysMenuUpdateOne) SetMetaNoBasicLayout(v int8) *SysMenuUpdateOne {
	_u.mutation.ResetMetaNoBasicLayout()
	_u.mutation.SetMetaNoBasicLayout(v)
	return _u
}

// SetNillableMetaNoBasicLayout sets the "meta_no_basic_layout" field if the given value is not nil.
func (_u *SysMenuUpdateOne) SetNillableMetaNoBasicLayout(v *int8) *SysMenuUpdateOne {
	if v != nil {
		_u.SetMetaNoBasicLayout(*v)
	}
	return _u
}

// AddMetaNoBasicLayout adds value to the "meta_no_basic_layout" field.
func (_u *SysMenuUpdateOne) AddMetaNoBasicLayout(v int8) *SysMenuUpdateOne {
	_u.mutation.AddMetaNoBasicLayout(v)
	return _u
}

// AddSysRoleIDs adds the "sysRoles" edge to the SysRole entity by IDs.
func (_u *SysMenuUpdateOne) AddSysRoleIDs(ids ...types.ID) *SysMenuUpdateOne {
	_u.mutation.AddSysRoleIDs(ids...)
	return _u
}

// AddSysRoles adds the "sysRoles" edges to the SysRole entity.
func (_u *SysMenuUpdateOne) AddSysRoles(v ...*SysRole) *SysMenuUpdateOne {
	ids := make([]types.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSysRoleIDs(ids...)
}

// SetParent sets the "parent" edge to the SysMenu entity.
func (_u *SysMenuUpdateOne) SetParent(v *SysMenu) *SysMenuUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the SysMenu entity by IDs.
func (_u *SysMenuUpdateOne) AddChildIDs(ids ...types.ID) *SysMenuUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the SysMenu entity.
func (_u *SysMenuUpdateOne) AddChildren(v ...*SysMenu) *SysMenuUpdateOne {
	ids := make([]types.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the SysMenuMutation object of the builder.
func (_u *SysMenuUpdateOne) Mutation() *SysMenuMutation {
	return _u.mutation
}

// ClearSysRoles clears all "sysRoles" edges to the SysRole entity.
func (_u *SysMenuUpdateOne) ClearSysRoles() *SysMenuUpdateOne {
	_u.mutation.ClearSysRoles()
	return _u
}

// RemoveSysRoleIDs removes the "sysRoles" edge to SysRole entities by IDs.
func (_u *SysMenuUpdateOne) RemoveSysRoleIDs(ids ...types.ID) *SysMenuUpdateOne {
	_u.mutation.RemoveSysRoleIDs(ids...)
	return _u
}

// RemoveSysRoles removes "sysRoles" edges to SysRole entities.
func (_u *SysMenuUpdateOne) RemoveSysRoles(v ...*SysRole) *SysMenuUpdateOne {
	ids := make([]types.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSysRoleIDs(ids...)
}

// ClearParent clears the "parent" edge to the SysMenu entity.
func (_u *SysMenuUpdateOne) ClearParent() *SysMenuUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the SysMenu entity.
func (_u *SysMenuUpdateOne) ClearChildren() *SysMenuUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to SysMenu entities by IDs.
func (_u *SysMenuUpdateOne) RemoveChildIDs(ids ...types.ID) *SysMenuUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to SysMenu entities.
func (_u *SysMenuUpdateOne) RemoveChildren(v ...*SysMenu) *SysMenuUpdateOne {
	ids := make([]types.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the SysMenuUpdate builder.
func (_u *SysMenuUpdateOne) Where(ps ...predicate.SysMenu) *SysMenuUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysMenuUpdateOne) Select(field string, fields ...string) *SysMenuUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysMenu entity.
func (_u *SysMenuUpdateOne) Save(ctx context.Context) (*SysMenu, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysMenuUpdateOne) SaveX(ctx context.Context) *SysMenu {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysMenuUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysMenuUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SysMenuUpdateOne) defaults() error {
	if _, ok := _u.mutation.CreatedAt(); !ok && !_u.mutation.CreatedAtCleared() {
		if sysmenu.UpdateDefaultCreatedAt == nil {
			return fmt.Errorf("entcore: uninitialized sysmenu.UpdateDefaultCreatedAt (forgotten import entcore/runtime?)")
		}
		v := sysmenu.UpdateDefaultCreatedAt()
		_u.mutation.SetCreatedAt(v)
	}
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		if sysmenu.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("entcore: uninitialized sysmenu.UpdateDefaultUpdatedAt (forgotten import entcore/runtime?)")
		}
		v := sysmenu.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *SysMenuUpdateOne) sqlSave(ctx context.Context) (_node *SysMenu, err error) {
	_spec := sqlgraph.NewUpdateSpec(sysmenu.Table, sysmenu.Columns, sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entcore: missing "SysMenu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysmenu.FieldID)
		for _, f := range fields {
			if !sysmenu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entcore: invalid field %q for query", f)}
			}
			if f != sysmenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(sysmenu.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(sysmenu.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sysmenu.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysmenu.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysmenu.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sysmenu.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(sysmenu.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysmenu.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysmenu.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysmenu.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(sysmenu.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(sysmenu.FieldDeletedBy, field.TypeString, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(sysmenu.FieldDeletedBy, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysmenu.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysmenu.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(sysmenu.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(sysmenu.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.DelFlag(); ok {
		_spec.SetField(sysmenu.FieldDelFlag, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDelFlag(); ok {
		_spec.AddField(sysmenu.FieldDelFlag, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sysmenu.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(sysmenu.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(sysmenu.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(sysmenu.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(sysmenu.FieldType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Component(); ok {
		_spec.SetField(sysmenu.FieldComponent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(sysmenu.FieldPermission, field.TypeString, value)
	}
	if _u.mutation.PermissionCleared() {
		_spec.ClearField(sysmenu.FieldPermission, field.TypeString)
	}
	if value, ok := _u.mutation.Redirect(); ok {
		_spec.SetField(sysmenu.FieldRedirect, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaTitle(); ok {
		_spec.SetField(sysmenu.FieldMetaTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaIcon(); ok {
		_spec.SetField(sysmenu.FieldMetaIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaActiveIcon(); ok {
		_spec.SetField(sysmenu.FieldMetaActiveIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaKeepAlive(); ok {
		_spec.SetField(sysmenu.FieldMetaKeepAlive, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaKeepAlive(); ok {
		_spec.AddField(sysmenu.FieldMetaKeepAlive, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaHideInMenu(); ok {
		_spec.SetField(sysmenu.FieldMetaHideInMenu, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaHideInMenu(); ok {
		_spec.AddField(sysmenu.FieldMetaHideInMenu, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaHideInTab(); ok {
		_spec.SetField(sysmenu.FieldMetaHideInTab, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaHideInTab(); ok {
		_spec.AddField(sysmenu.FieldMetaHideInTab, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaHideInBreadcrumb(); ok {
		_spec.SetField(sysmenu.FieldMetaHideInBreadcrumb, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaHideInBreadcrumb(); ok {
		_spec.AddField(sysmenu.FieldMetaHideInBreadcrumb, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaHideChildrenInMenu(); ok {
		_spec.SetField(sysmenu.FieldMetaHideChildrenInMenu, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaHideChildrenInMenu(); ok {
		_spec.AddField(sysmenu.FieldMetaHideChildrenInMenu, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaAuthority(); ok {
		_spec.SetField(sysmenu.FieldMetaAuthority, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaBadge(); ok {
		_spec.SetField(sysmenu.FieldMetaBadge, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaBadgeType(); ok {
		_spec.SetField(sysmenu.FieldMetaBadgeType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaBadgeType(); ok {
		_spec.AddField(sysmenu.FieldMetaBadgeType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaBadgeVariants(); ok {
		_spec.SetField(sysmenu.FieldMetaBadgeVariants, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaBadgeVariants(); ok {
		_spec.AddField(sysmenu.FieldMetaBadgeVariants, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaFullPathKey(); ok {
		_spec.SetField(sysmenu.FieldMetaFullPathKey, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaFullPathKey(); ok {
		_spec.AddField(sysmenu.FieldMetaFullPathKey, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaActivePath(); ok {
		_spec.SetField(sysmenu.FieldMetaActivePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaAffixTab(); ok {
		_spec.SetField(sysmenu.FieldMetaAffixTab, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaAffixTab(); ok {
		_spec.AddField(sysmenu.FieldMetaAffixTab, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaAffixTabOrder(); ok {
		_spec.SetField(sysmenu.FieldMetaAffixTabOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetaAffixTabOrder(); ok {
		_spec.AddField(sysmenu.FieldMetaAffixTabOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetaIframeSrc(); ok {
		_spec.SetField(sysmenu.FieldMetaIframeSrc, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaIgnoreAccess(); ok {
		_spec.SetField(sysmenu.FieldMetaIgnoreAccess, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaIgnoreAccess(); ok {
		_spec.AddField(sysmenu.FieldMetaIgnoreAccess, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaLink(); ok {
		_spec.SetField(sysmenu.FieldMetaLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaMaxNumOfOpenTab(); ok {
		_spec.SetField(sysmenu.FieldMetaMaxNumOfOpenTab, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetaMaxNumOfOpenTab(); ok {
		_spec.AddField(sysmenu.FieldMetaMaxNumOfOpenTab, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetaMenuVisibleWithForbidden(); ok {
		_spec.SetField(sysmenu.FieldMetaMenuVisibleWithForbidden, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaMenuVisibleWithForbidden(); ok {
		_spec.AddField(sysmenu.FieldMetaMenuVisibleWithForbidden, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaOpenInNewWindow(); ok {
		_spec.SetField(sysmenu.FieldMetaOpenInNewWindow, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaOpenInNewWindow(); ok {
		_spec.AddField(sysmenu.FieldMetaOpenInNewWindow, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.MetaOrder(); ok {
		_spec.SetField(sysmenu.FieldMetaOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetaOrder(); ok {
		_spec.AddField(sysmenu.FieldMetaOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetaQuery(); ok {
		_spec.SetField(sysmenu.FieldMetaQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetaNoBasicLayout(); ok {
		_spec.SetField(sysmenu.FieldMetaNoBasicLayout, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMetaNoBasicLayout(); ok {
		_spec.AddField(sysmenu.FieldMetaNoBasicLayout, field.TypeInt8, value)
	}
	if _u.mutation.SysRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   sysmenu.SysRolesTable,
			Columns: sysmenu.SysRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSysRolesIDs(); len(nodes) > 0 && !_u.mutation.SysRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   sysmenu.SysRolesTable,
			Columns: sysmenu.SysRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SysRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   sysmenu.SysRolesTable,
			Columns: sysmenu.SysRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysmenu.ParentTable,
			Columns: []string{sysmenu.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysmenu.ParentTable,
			Columns: []string{sysmenu.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysmenu.ChildrenTable,
			Columns: []string{sysmenu.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysmenu.ChildrenTable,
			Columns: []string{sysmenu.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysmenu.ChildrenTable,
			Columns: []string{sysmenu.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SysMenu{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
