// Code generated by ent, DO NOT EDIT.

package entcore

import (
	"fmt"
	"go-ent-demo/entcore/sysrole"
	"go-ent-demo/types"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 系统角色表
type SysRole struct {
	config `json:"-"`
	// ID of the ent.
	ID types.ID `json:"id"`
	// Sort holds the value of the "sort" field.
	Sort int `json:"sort"`
	// Status holds the value of the "status" field.
	Status string `json:"status"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"createdBy"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt types.CustomTime `json:"createdAt"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updatedBy"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt types.CustomTime `json:"updatedAt"`
	// DeletedBy holds the value of the "deleted_by" field.
	DeletedBy string `json:"-"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"-"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark"`
	// 角色名称
	RoleName string `json:"roleName"`
	// 角色编码
	RoleCode string `json:"roleCode"`
	// 菜单树选择项是否关联显示
	MenuCheckStrictly int8 `json:"menuCheckStrictly"`
	// 部门树选择项是否关联显示
	DeptCheckStrictly int8 `json:"deptCheckStrictly"`
	// 数据权限范围(1全部数据权限 2自定义数据权限 3本部门数据权限 4本部门及以下数据权限)
	DataScope int8 `json:"dataScope"`
	// 角色描述
	Description string `json:"description"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysRoleQuery when eager-loading is set.
	Edges        SysRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysRoleEdges holds the relations/edges for other nodes in the graph.
type SysRoleEdges struct {
	// SysDepts holds the value of the sysDepts edge.
	SysDepts []*SysDept `json:"sysDepts,omitempty"`
	// SysUsers holds the value of the sysUsers edge.
	SysUsers []*SysUser `json:"sysUsers,omitempty"`
	// SysMenus holds the value of the sysMenus edge.
	SysMenus []*SysMenu `json:"sysMenus,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SysDeptsOrErr returns the SysDepts value or an error if the edge
// was not loaded in eager-loading.
func (e SysRoleEdges) SysDeptsOrErr() ([]*SysDept, error) {
	if e.loadedTypes[0] {
		return e.SysDepts, nil
	}
	return nil, &NotLoadedError{edge: "sysDepts"}
}

// SysUsersOrErr returns the SysUsers value or an error if the edge
// was not loaded in eager-loading.
func (e SysRoleEdges) SysUsersOrErr() ([]*SysUser, error) {
	if e.loadedTypes[1] {
		return e.SysUsers, nil
	}
	return nil, &NotLoadedError{edge: "sysUsers"}
}

// SysMenusOrErr returns the SysMenus value or an error if the edge
// was not loaded in eager-loading.
func (e SysRoleEdges) SysMenusOrErr() ([]*SysMenu, error) {
	if e.loadedTypes[2] {
		return e.SysMenus, nil
	}
	return nil, &NotLoadedError{edge: "sysMenus"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysrole.FieldSort, sysrole.FieldMenuCheckStrictly, sysrole.FieldDeptCheckStrictly, sysrole.FieldDataScope:
			values[i] = new(sql.NullInt64)
		case sysrole.FieldStatus, sysrole.FieldCreatedBy, sysrole.FieldUpdatedBy, sysrole.FieldDeletedBy, sysrole.FieldRemark, sysrole.FieldRoleName, sysrole.FieldRoleCode, sysrole.FieldDescription:
			values[i] = new(sql.NullString)
		case sysrole.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case sysrole.FieldCreatedAt, sysrole.FieldUpdatedAt:
			values[i] = new(types.CustomTime)
		case sysrole.FieldID:
			values[i] = new(types.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysRole fields.
func (_m *SysRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysrole.FieldID:
			if value, ok := values[i].(*types.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case sysrole.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		case sysrole.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case sysrole.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case sysrole.FieldCreatedAt:
			if value, ok := values[i].(*types.CustomTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value != nil {
				_m.CreatedAt = *value
			}
		case sysrole.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case sysrole.FieldUpdatedAt:
			if value, ok := values[i].(*types.CustomTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value != nil {
				_m.UpdatedAt = *value
			}
		case sysrole.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = value.String
			}
		case sysrole.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case sysrole.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case sysrole.FieldRoleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_name", values[i])
			} else if value.Valid {
				_m.RoleName = value.String
			}
		case sysrole.FieldRoleCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_code", values[i])
			} else if value.Valid {
				_m.RoleCode = value.String
			}
		case sysrole.FieldMenuCheckStrictly:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field menu_check_strictly", values[i])
			} else if value.Valid {
				_m.MenuCheckStrictly = int8(value.Int64)
			}
		case sysrole.FieldDeptCheckStrictly:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dept_check_strictly", values[i])
			} else if value.Valid {
				_m.DeptCheckStrictly = int8(value.Int64)
			}
		case sysrole.FieldDataScope:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field data_scope", values[i])
			} else if value.Valid {
				_m.DataScope = int8(value.Int64)
			}
		case sysrole.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysRole.
// This includes values selected through modifiers, order, etc.
func (_m *SysRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySysDepts queries the "sysDepts" edge of the SysRole entity.
func (_m *SysRole) QuerySysDepts() *SysDeptQuery {
	return NewSysRoleClient(_m.config).QuerySysDepts(_m)
}

// QuerySysUsers queries the "sysUsers" edge of the SysRole entity.
func (_m *SysRole) QuerySysUsers() *SysUserQuery {
	return NewSysRoleClient(_m.config).QuerySysUsers(_m)
}

// QuerySysMenus queries the "sysMenus" edge of the SysRole entity.
func (_m *SysRole) QuerySysMenus() *SysMenuQuery {
	return NewSysRoleClient(_m.config).QuerySysMenus(_m)
}

// Update returns a builder for updating this SysRole.
// Note that you need to call SysRole.Unwrap() before calling this method if this SysRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysRole) Update() *SysRoleUpdateOne {
	return NewSysRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysRole) Unwrap() *SysRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("entcore: SysRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysRole) String() string {
	var builder strings.Builder
	builder.WriteString("SysRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_by=")
	builder.WriteString(_m.DeletedBy)
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("role_name=")
	builder.WriteString(_m.RoleName)
	builder.WriteString(", ")
	builder.WriteString("role_code=")
	builder.WriteString(_m.RoleCode)
	builder.WriteString(", ")
	builder.WriteString("menu_check_strictly=")
	builder.WriteString(fmt.Sprintf("%v", _m.MenuCheckStrictly))
	builder.WriteString(", ")
	builder.WriteString("dept_check_strictly=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeptCheckStrictly))
	builder.WriteString(", ")
	builder.WriteString("data_scope=")
	builder.WriteString(fmt.Sprintf("%v", _m.DataScope))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// SysRoles is a parsable slice of SysRole.
type SysRoles []*SysRole
