// Code generated by ent, DO NOT EDIT.

package role

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the role type in the database.
	Label = "role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoleName holds the string denoting the role_name field in the database.
	FieldRoleName = "role_name"
	// FieldRoleCode holds the string denoting the role_code field in the database.
	FieldRoleCode = "role_code"
	// EdgeSysDepts holds the string denoting the sysdepts edge name in mutations.
	EdgeSysDepts = "sysDepts"
	// EdgeSysUsers holds the string denoting the sysusers edge name in mutations.
	EdgeSysUsers = "sysUsers"
	// Table holds the table name of the role in the database.
	Table = "role"
	// SysDeptsTable is the table that holds the sysDepts relation/edge. The primary key declared below.
	SysDeptsTable = "sys_role_dept"
	// SysDeptsInverseTable is the table name for the Dept entity.
	// It exists in this package in order to avoid circular dependency with the "dept" package.
	SysDeptsInverseTable = "dept"
	// SysUsersTable is the table that holds the sysUsers relation/edge. The primary key declared below.
	SysUsersTable = "sys_user_role"
	// SysUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	SysUsersInverseTable = "user"
)

// Columns holds all SQL columns for role fields.
var Columns = []string{
	FieldID,
	FieldRoleName,
	FieldRoleCode,
}

var (
	// SysDeptsPrimaryKey and SysDeptsColumn2 are the table columns denoting the
	// primary key for the sysDepts relation (M2M).
	SysDeptsPrimaryKey = []string{"role_id", "dept_id"}
	// SysUsersPrimaryKey and SysUsersColumn2 are the table columns denoting the
	// primary key for the sysUsers relation (M2M).
	SysUsersPrimaryKey = []string{"user_id", "role_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Role queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRoleName orders the results by the role_name field.
func ByRoleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleName, opts...).ToFunc()
}

// ByRoleCode orders the results by the role_code field.
func ByRoleCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleCode, opts...).ToFunc()
}

// BySysDeptsCount orders the results by sysDepts count.
func BySysDeptsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSysDeptsStep(), opts...)
	}
}

// BySysDepts orders the results by sysDepts terms.
func BySysDepts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSysDeptsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySysUsersCount orders the results by sysUsers count.
func BySysUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSysUsersStep(), opts...)
	}
}

// BySysUsers orders the results by sysUsers terms.
func BySysUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSysUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSysDeptsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SysDeptsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, SysDeptsTable, SysDeptsPrimaryKey...),
	)
}
func newSysUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SysUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, SysUsersTable, SysUsersPrimaryKey...),
	)
}
